--==========================================================================================================================	
-- GreatWorks
--==========================================================================================================================	
INSERT INTO GreatWorks 
			(Type, 						GreatWorkClassType,			Description,								Quote,												Audio,							Image)
VALUES		('GREAT_WORK_SKALD_01', 	'GREAT_WORK_LITERATURE',	'TXT_KEY_GREAT_WORK_SKALD_GREAT_WORK_01',	'TXT_KEY_GREAT_WORK_QUOTE_SKALD_GREAT_WORK_01',		'AS2D_GREAT_ARTIST_ARTWORK',	'GreatWriter_Background.dds'),
			('GREAT_WORK_SKALD_02', 	'GREAT_WORK_LITERATURE',	'TXT_KEY_GREAT_WORK_SKALD_GREAT_WORK_02',	'TXT_KEY_GREAT_WORK_QUOTE_SKALD_GREAT_WORK_02',		'AS2D_GREAT_ARTIST_ARTWORK',	'GreatWriter_Background.dds'),
			('GREAT_WORK_SKALD_03', 	'GREAT_WORK_LITERATURE',	'TXT_KEY_GREAT_WORK_SKALD_GREAT_WORK_03',	'TXT_KEY_GREAT_WORK_QUOTE_SKALD_GREAT_WORK_03',		'AS2D_GREAT_ARTIST_ARTWORK',	'GreatWriter_Background.dds'),
			('GREAT_WORK_SKALD_04', 	'GREAT_WORK_LITERATURE',	'TXT_KEY_GREAT_WORK_SKALD_GREAT_WORK_04',	'TXT_KEY_GREAT_WORK_QUOTE_SKALD_GREAT_WORK_04',		'AS2D_GREAT_ARTIST_ARTWORK',	'GreatWriter_Background.dds'),
			('GREAT_WORK_SKALD_05', 	'GREAT_WORK_LITERATURE',	'TXT_KEY_GREAT_WORK_SKALD_GREAT_WORK_05',	'TXT_KEY_GREAT_WORK_QUOTE_SKALD_GREAT_WORK_05',		'AS2D_GREAT_ARTIST_ARTWORK',	'GreatWriter_Background.dds'),
			('GREAT_WORK_SKALD_06', 	'GREAT_WORK_LITERATURE',	'TXT_KEY_GREAT_WORK_SKALD_GREAT_WORK_06',	'TXT_KEY_GREAT_WORK_QUOTE_SKALD_GREAT_WORK_06',		'AS2D_GREAT_ARTIST_ARTWORK',	'GreatWriter_Background.dds'),
			('GREAT_WORK_SKALD_07', 	'GREAT_WORK_LITERATURE',	'TXT_KEY_GREAT_WORK_SKALD_GREAT_WORK_07',	'TXT_KEY_GREAT_WORK_QUOTE_SKALD_GREAT_WORK_07',		'AS2D_GREAT_ARTIST_ARTWORK',	'GreatWriter_Background.dds'),
			('GREAT_WORK_SKALD_08', 	'GREAT_WORK_LITERATURE',	'TXT_KEY_GREAT_WORK_SKALD_GREAT_WORK_08',	'TXT_KEY_GREAT_WORK_QUOTE_SKALD_GREAT_WORK_08',		'AS2D_GREAT_ARTIST_ARTWORK',	'GreatWriter_Background.dds'),
			('GREAT_WORK_SKALD_09', 	'GREAT_WORK_LITERATURE',	'TXT_KEY_GREAT_WORK_SKALD_GREAT_WORK_09',	'TXT_KEY_GREAT_WORK_QUOTE_SKALD_GREAT_WORK_09',		'AS2D_GREAT_ARTIST_ARTWORK',	'GreatWriter_Background.dds'),
			('GREAT_WORK_SKALD_10', 	'GREAT_WORK_LITERATURE',	'TXT_KEY_GREAT_WORK_SKALD_GREAT_WORK_10',	'TXT_KEY_GREAT_WORK_QUOTE_SKALD_GREAT_WORK_10',		'AS2D_GREAT_ARTIST_ARTWORK',	'GreatWriter_Background.dds'),
			('GREAT_WORK_SKALD_11', 	'GREAT_WORK_LITERATURE',	'TXT_KEY_GREAT_WORK_SKALD_GREAT_WORK_11',	'TXT_KEY_GREAT_WORK_QUOTE_SKALD_GREAT_WORK_11',		'AS2D_GREAT_ARTIST_ARTWORK',	'GreatWriter_Background.dds'),
			('GREAT_WORK_SKALD_12', 	'GREAT_WORK_LITERATURE',	'TXT_KEY_GREAT_WORK_SKALD_GREAT_WORK_12',	'TXT_KEY_GREAT_WORK_QUOTE_SKALD_GREAT_WORK_12',		'AS2D_GREAT_ARTIST_ARTWORK',	'GreatWriter_Background.dds'),
			('GREAT_WORK_SKALD_13', 	'GREAT_WORK_LITERATURE',	'TXT_KEY_GREAT_WORK_SKALD_GREAT_WORK_13',	'TXT_KEY_GREAT_WORK_QUOTE_SKALD_GREAT_WORK_13',		'AS2D_GREAT_ARTIST_ARTWORK',	'GreatWriter_Background.dds'),
			('GREAT_WORK_SKALD_14', 	'GREAT_WORK_LITERATURE',	'TXT_KEY_GREAT_WORK_SKALD_GREAT_WORK_14',	'TXT_KEY_GREAT_WORK_QUOTE_SKALD_GREAT_WORK_14',		'AS2D_GREAT_ARTIST_ARTWORK',	'GreatWriter_Background.dds'),
			('GREAT_WORK_SKALD_15', 	'GREAT_WORK_LITERATURE',	'TXT_KEY_GREAT_WORK_SKALD_GREAT_WORK_15',	'TXT_KEY_GREAT_WORK_QUOTE_SKALD_GREAT_WORK_15',		'AS2D_GREAT_ARTIST_ARTWORK',	'GreatWriter_Background.dds'),
			('GREAT_WORK_SKALD_16', 	'GREAT_WORK_LITERATURE',	'TXT_KEY_GREAT_WORK_SKALD_GREAT_WORK_16',	'TXT_KEY_GREAT_WORK_QUOTE_SKALD_GREAT_WORK_16',		'AS2D_GREAT_ARTIST_ARTWORK',	'GreatWriter_Background.dds'),
			('GREAT_WORK_SKALD_17', 	'GREAT_WORK_LITERATURE',	'TXT_KEY_GREAT_WORK_SKALD_GREAT_WORK_17',	'TXT_KEY_GREAT_WORK_QUOTE_SKALD_GREAT_WORK_17',		'AS2D_GREAT_ARTIST_ARTWORK',	'GreatWriter_Background.dds'),
			('GREAT_WORK_SKALD_18', 	'GREAT_WORK_LITERATURE',	'TXT_KEY_GREAT_WORK_SKALD_GREAT_WORK_18',	'TXT_KEY_GREAT_WORK_QUOTE_SKALD_GREAT_WORK_18',		'AS2D_GREAT_ARTIST_ARTWORK',	'GreatWriter_Background.dds'),
			('GREAT_WORK_SKALD_19', 	'GREAT_WORK_LITERATURE',	'TXT_KEY_GREAT_WORK_SKALD_GREAT_WORK_19',	'TXT_KEY_GREAT_WORK_QUOTE_SKALD_GREAT_WORK_19',		'AS2D_GREAT_ARTIST_ARTWORK',	'GreatWriter_Background.dds'),
			('GREAT_WORK_SKALD_20', 	'GREAT_WORK_LITERATURE',	'TXT_KEY_GREAT_WORK_SKALD_GREAT_WORK_20',	'TXT_KEY_GREAT_WORK_QUOTE_SKALD_GREAT_WORK_20',		'AS2D_GREAT_ARTIST_ARTWORK',	'GreatWriter_Background.dds'),
			('GREAT_WORK_SKALD_21', 	'GREAT_WORK_LITERATURE',	'TXT_KEY_GREAT_WORK_SKALD_GREAT_WORK_21',	'TXT_KEY_GREAT_WORK_QUOTE_SKALD_GREAT_WORK_21',		'AS2D_GREAT_ARTIST_ARTWORK',	'GreatWriter_Background.dds'),
			('GREAT_WORK_SKALD_22', 	'GREAT_WORK_LITERATURE',	'TXT_KEY_GREAT_WORK_SKALD_GREAT_WORK_22',	'TXT_KEY_GREAT_WORK_QUOTE_SKALD_GREAT_WORK_22',		'AS2D_GREAT_ARTIST_ARTWORK',	'GreatWriter_Background.dds'),
			('GREAT_WORK_SKALD_23', 	'GREAT_WORK_LITERATURE',	'TXT_KEY_GREAT_WORK_SKALD_GREAT_WORK_23',	'TXT_KEY_GREAT_WORK_QUOTE_SKALD_GREAT_WORK_23',		'AS2D_GREAT_ARTIST_ARTWORK',	'GreatWriter_Background.dds'),
			('GREAT_WORK_SKALD_24', 	'GREAT_WORK_LITERATURE',	'TXT_KEY_GREAT_WORK_SKALD_GREAT_WORK_24',	'TXT_KEY_GREAT_WORK_QUOTE_SKALD_GREAT_WORK_24',		'AS2D_GREAT_ARTIST_ARTWORK',	'GreatWriter_Background.dds'),
			('GREAT_WORK_SKALD_25', 	'GREAT_WORK_LITERATURE',	'TXT_KEY_GREAT_WORK_SKALD_GREAT_WORK_25',	'TXT_KEY_GREAT_WORK_QUOTE_SKALD_GREAT_WORK_25',		'AS2D_GREAT_ARTIST_ARTWORK',	'GreatWriter_Background.dds'),
			('GREAT_WORK_SKALD_26', 	'GREAT_WORK_LITERATURE',	'TXT_KEY_GREAT_WORK_SKALD_GREAT_WORK_26',	'TXT_KEY_GREAT_WORK_QUOTE_SKALD_GREAT_WORK_26',		'AS2D_GREAT_ARTIST_ARTWORK',	'GreatWriter_Background.dds'),
			('GREAT_WORK_SKALD_27', 	'GREAT_WORK_LITERATURE',	'TXT_KEY_GREAT_WORK_SKALD_GREAT_WORK_27',	'TXT_KEY_GREAT_WORK_QUOTE_SKALD_GREAT_WORK_27',		'AS2D_GREAT_ARTIST_ARTWORK',	'GreatWriter_Background.dds'),
			('GREAT_WORK_SKALD_28', 	'GREAT_WORK_LITERATURE',	'TXT_KEY_GREAT_WORK_SKALD_GREAT_WORK_28',	'TXT_KEY_GREAT_WORK_QUOTE_SKALD_GREAT_WORK_28',		'AS2D_GREAT_ARTIST_ARTWORK',	'GreatWriter_Background.dds'),
			('GREAT_WORK_SKALD_29', 	'GREAT_WORK_LITERATURE',	'TXT_KEY_GREAT_WORK_SKALD_GREAT_WORK_29',	'TXT_KEY_GREAT_WORK_QUOTE_SKALD_GREAT_WORK_29',		'AS2D_GREAT_ARTIST_ARTWORK',	'GreatWriter_Background.dds'),
			('GREAT_WORK_SKALD_30', 	'GREAT_WORK_LITERATURE',	'TXT_KEY_GREAT_WORK_SKALD_GREAT_WORK_30',	'TXT_KEY_GREAT_WORK_QUOTE_SKALD_GREAT_WORK_30',		'AS2D_GREAT_ARTIST_ARTWORK',	'GreatWriter_Background.dds');
--==========================================================================================================================		
--==========================================================================================================================	
