	
INSERT INTO Civilization_CityNames
			(CivilizationType, 			CityName)
VALUES		('CIVILIZATION_TUSCANY', 	'TXT_KEY_CITY_NAME_TUSCANY_FLORENCE'),
			('CIVILIZATION_TUSCANY', 	'TXT_KEY_CITY_NAME_TUSCANY_PISA'),
			('CIVILIZATION_TUSCANY', 	'TXT_KEY_CITY_NAME_TUSCANY_SIENA'),
			('CIVILIZATION_TUSCANY', 	'TXT_KEY_CITY_NAME_TUSCANY_LUCCA'),
			('CIVILIZATION_TUSCANY', 	'TXT_KEY_CITY_NAME_TUSCANY_AREZZO'),
			('CIVILIZATION_TUSCANY', 	'TXT_KEY_CITY_NAME_TUSCANY_PRATO'),
			('CIVILIZATION_TUSCANY', 	'TXT_KEY_CITY_NAME_TUSCANY_GROSSETO'),
			('CIVILIZATION_TUSCANY', 	'TXT_KEY_CITY_NAME_TUSCANY_SAN_GIMIGNANO'),
			('CIVILIZATION_TUSCANY', 	'TXT_KEY_CITY_NAME_TUSCANY_FIESOLE'),
			('CIVILIZATION_TUSCANY', 	'TXT_KEY_CITY_NAME_TUSCANY_PIETRASANTA'),
			('CIVILIZATION_TUSCANY', 	'TXT_KEY_CITY_NAME_TUSCANY_PISTOIA'),
			('CIVILIZATION_TUSCANY', 	'TXT_KEY_CITY_NAME_TUSCANY_CARRARA'),
			('CIVILIZATION_TUSCANY', 	'TXT_KEY_CITY_NAME_TUSCANY_PIENZA'),
			('CIVILIZATION_TUSCANY', 	'TXT_KEY_CITY_NAME_TUSCANY_VOLTERRA'),
			('CIVILIZATION_TUSCANY', 	'TXT_KEY_CITY_NAME_TUSCANY_LIVORNO'),
			('CIVILIZATION_TUSCANY', 	'TXT_KEY_CITY_NAME_TUSCANY_CORTONA'),
			('CIVILIZATION_TUSCANY', 	'TXT_KEY_CITY_NAME_TUSCANY_MONTEPULCIANO'),
			('CIVILIZATION_TUSCANY', 	'TXT_KEY_CITY_NAME_TUSCANY_VIAREGGIO'),
			('CIVILIZATION_TUSCANY', 	'TXT_KEY_CITY_NAME_TUSCANY_PITIGLIANO'),
			('CIVILIZATION_TUSCANY', 	'TXT_KEY_CITY_NAME_TUSCANY_CASTIGLION_FIORENTINO'),
			('CIVILIZATION_TUSCANY', 	'TXT_KEY_CITY_NAME_TUSCANY_LUCIGNANO'),
			('CIVILIZATION_TUSCANY', 	'TXT_KEY_CITY_NAME_TUSCANY_SANSEPOLCRO'),
			('CIVILIZATION_TUSCANY', 	'TXT_KEY_CITY_NAME_TUSCANY_CERTALDO'),
			('CIVILIZATION_TUSCANY', 	'TXT_KEY_CITY_NAME_TUSCANY_ORBETELLO'),
			('CIVILIZATION_TUSCANY', 	'TXT_KEY_CITY_NAME_TUSCANY_PIOMBINO'),
			('CIVILIZATION_TUSCANY', 	'TXT_KEY_CITY_NAME_TUSCANY_BARGA'),
			('CIVILIZATION_TUSCANY', 	'TXT_KEY_CITY_NAME_TUSCANY_CARMIGNANO'),
			('CIVILIZATION_TUSCANY', 	'TXT_KEY_CITY_NAME_TUSCANY_MONTALCINO'),
			('CIVILIZATION_TUSCANY', 	'TXT_KEY_CITY_NAME_TUSCANY_SUVERETO'),
			('CIVILIZATION_TUSCANY', 	'TXT_KEY_CITY_NAME_TUSCANY_POPPI'),
			('CIVILIZATION_TUSCANY', 	'TXT_KEY_CITY_NAME_TUSCANY_FIVIZZANO'),
			('CIVILIZATION_TUSCANY', 	'TXT_KEY_CITY_NAME_TUSCANY_PONTREMOLI'),
			('CIVILIZATION_TUSCANY', 	'TXT_KEY_CITY_NAME_TUSCANY_PESCIA'),
			('CIVILIZATION_TUSCANY', 	'TXT_KEY_CITY_NAME_TUSCANY_SCANDICCI'),
			('CIVILIZATION_TUSCANY', 	'TXT_KEY_CITY_NAME_TUSCANY_MONTEVARCHI'),
			('CIVILIZATION_TUSCANY', 	'TXT_KEY_CITY_NAME_TUSCANY_PONTEDERA'),
			('CIVILIZATION_TUSCANY', 	'TXT_KEY_CITY_NAME_TUSCANY_QUARRATA'),
			('CIVILIZATION_TUSCANY', 	'TXT_KEY_CITY_NAME_TUSCANY_EMPOLI'),
			('CIVILIZATION_TUSCANY', 	'TXT_KEY_CITY_NAME_TUSCANY_MONTERIGGIONI'),
			('CIVILIZATION_TUSCANY', 	'TXT_KEY_CITY_NAME_TUSCANY_VINCI');
--==========================================================================================================================	
-- Civilization_Religions
--==========================================================================================================================		
INSERT INTO Civilization_Religions 
			(CivilizationType, 				ReligionType)
VALUES		('CIVILIZATION_TUSCANY', 		'RELIGION_CHRISTIANITY');
--==========================================================================================================================	
-- Civilization_SpyNames
--==========================================================================================================================	
INSERT INTO Civilization_SpyNames 
			(CivilizationType, 				SpyName)
VALUES		('CIVILIZATION_TUSCANY', 		'TXT_KEY_SPY_NAME_TUSCANY_0'),
			('CIVILIZATION_TUSCANY', 		'TXT_KEY_SPY_NAME_TUSCANY_1'),
			('CIVILIZATION_TUSCANY', 		'TXT_KEY_SPY_NAME_TUSCANY_2'),
			('CIVILIZATION_TUSCANY', 		'TXT_KEY_SPY_NAME_TUSCANY_3'),
			('CIVILIZATION_TUSCANY', 		'TXT_KEY_SPY_NAME_TUSCANY_4'),
			('CIVILIZATION_TUSCANY', 		'TXT_KEY_SPY_NAME_TUSCANY_5'),
			('CIVILIZATION_TUSCANY', 		'TXT_KEY_SPY_NAME_TUSCANY_6'),
			('CIVILIZATION_TUSCANY', 		'TXT_KEY_SPY_NAME_TUSCANY_7'),
			('CIVILIZATION_TUSCANY', 		'TXT_KEY_SPY_NAME_TUSCANY_8'),
			('CIVILIZATION_TUSCANY', 		'TXT_KEY_SPY_NAME_TUSCANY_9');
--==========================================================================================================================		
--==========================================================================================================================