-- Insert SQL Rules Here 
UPDATE Civilization_Religions SET ReligionType = 
	( CASE WHEN EXISTS(SELECT Type FROM Religions WHERE Type="RELIGION_WAKAN_TANKA" )
		THEN "RELIGION_WAKAN_TANKA"
		ELSE "RELIGION_PROTESTANTISM" END
	) WHERE CivilizationType = "CIVILIZATION_THECREEFIRSTNATION";