UPDATE Civilization_Religions SET ReligionType = 
	( CASE WHEN EXISTS(SELECT Type FROM Religions WHERE Type="RELIGION_WILTRAN_MAPU" )
		THEN "RELIGION_WILTRAN_MAPU"
		ELSE "RELIGION_CHRISTIANITY" END
	) WHERE CivilizationType = "CIVILIZATION_MAPUCHE";