CREATE TABLE IF NOT EXISTS ML_CivCultures (ID INTEGER PRIMARY KEY AUTOINCREMENT, CivType TEXT, CultureType TEXT, CultureEra TEXT DEFAULT 'ANY');
INSERT INTO ML_CivCultures(CivType, CultureType, CultureEra)
SELECT 'CIVILIZATION_LEUGI_PHILISTINE', 'ARABIAN', 'ANY' ;