CREATE TRIGGER SwitchfromXiatoShangDynasty
AFTER INSERT ON Buildings WHEN 'BUILDING_XIA_SHANG_SWITCH' = NEW.Type
BEGIN

	UPDATE Civilizations SET Description = 'TXT_KEY_XIA_SHANG_MOD_DESC' WHERE Type = 'CIVILIZATION_ERLITOU_MOD';
	UPDATE Civilizations SET ShortDescription = 'TXT_KEY_XIA_SHANG_MOD_SHORT_DESC' WHERE Type = 'CIVILIZATION_ERLITOU_MOD';
	UPDATE Civilizations SET Adjective = 'TXT_KEY_XIA_SHANG_MOD_ADJECTIVE' WHERE Type = 'CIVILIZATION_ERLITOU_MOD';
	UPDATE Civilizations SET CivilopediaTag = 'TXT_KEY_CIVLOPEDIA_XIA_SHANG_MOD' WHERE Type = 'CIVILIZATION_ERLITOU_MOD';
	UPDATE Civilizations SET MapImage = 'XiaShangMapMod.dds' WHERE Type = 'CIVILIZATION_ERLITOU_MOD';
	UPDATE Civilizations SET DawnOfManQuote = 'TXT_KEY_DAWN_OF_MAN_ERLITOU_SHANG_MOD_TEXT' WHERE Type = 'CIVILIZATION_ERLITOU_MOD';
	UPDATE Civilizations SET DawnOfManImage = 'XiaShangDoMMod.dds' WHERE Type = 'CIVILIZATION_ERLITOU_MOD';
	UPDATE Civilizations SET DawnOfManAudio = 'NULL' WHERE Type = 'CIVILIZATION_ERLITOU_MOD';

	DELETE FROM Civilization_CityNames WHERE CivilizationType IN ('CIVILIZATION_ERLITOU_MOD');

	INSERT INTO Civilization_CityNames
			(CivilizationType,					CityName)
	VALUES  ('CIVILIZATION_ERLITOU_MOD',		'TXT_KEY_CITY_NAME_XIA_SHANG_MOD_YIN'),
			('CIVILIZATION_ERLITOU_MOD',		'TXT_KEY_CITY_NAME_XIA_SHANG_MOD_BO'),
			('CIVILIZATION_ERLITOU_MOD',		'TXT_KEY_CITY_NAME_XIA_SHANG_MOD_FAN'),
			('CIVILIZATION_ERLITOU_MOD',		'TXT_KEY_CITY_NAME_XIA_SHANG_MOD_XIAO'),
			('CIVILIZATION_ERLITOU_MOD',		'TXT_KEY_CITY_NAME_XIA_SHANG_MOD_DISHI'),
			('CIVILIZATION_ERLITOU_MOD',		'TXT_KEY_CITY_NAME_XIA_SHANG_MOD_BI'),
			('CIVILIZATION_ERLITOU_MOD',		'TXT_KEY_CITY_NAME_XIA_SHANG_MOD_YANSHI'),
			('CIVILIZATION_ERLITOU_MOD',		'TXT_KEY_CITY_NAME_XIA_SHANG_MOD_XIANG'),
			('CIVILIZATION_ERLITOU_MOD',		'TXT_KEY_CITY_NAME_XIA_SHANG_MOD_SHANGQIU'),
			('CIVILIZATION_ERLITOU_MOD',		'TXT_KEY_CITY_NAME_XIA_SHANG_MOD_PUGU'),
			('CIVILIZATION_ERLITOU_MOD',		'TXT_KEY_CITY_NAME_XIA_SHANG_MOD_AO'),
			('CIVILIZATION_ERLITOU_MOD',		'TXT_KEY_CITY_NAME_XIA_SHANG_MOD_GENG'),
			('CIVILIZATION_ERLITOU_MOD',		'TXT_KEY_CITY_NAME_XIA_SHANG_MOD_BEIMENG'),
			('CIVILIZATION_ERLITOU_MOD',		'TXT_KEY_CITY_NAME_XIA_SHANG_MOD_MO'),
			('CIVILIZATION_ERLITOU_MOD',		'TXT_KEY_CITY_NAME_XIA_SHANG_MOD_CHAOGE'),
			('CIVILIZATION_ERLITOU_MOD',		'TXT_KEY_CITY_NAME_XIA_SHANG_MOD_SHIXIANGGOU'),
			('CIVILIZATION_ERLITOU_MOD',		'TXT_KEY_CITY_NAME_XIA_SHANG_MOD_PANLONGCHENG'),
			('CIVILIZATION_ERLITOU_MOD',		'TXT_KEY_CITY_NAME_XIA_SHANG_MOD_HUANBEI'),
			('CIVILIZATION_ERLITOU_MOD',		'TXT_KEY_CITY_NAME_XIA_SHANG_MOD_ZHENGZHOU'),
			('CIVILIZATION_ERLITOU_MOD',		'TXT_KEY_CITY_NAME_XIA_SHANG_MOD_XINGAN'),
			('CIVILIZATION_ERLITOU_MOD',		'TXT_KEY_CITY_NAME_XIA_SHANG_MOD_DANSHAN'),
			('CIVILIZATION_ERLITOU_MOD',		'TXT_KEY_CITY_NAME_XIA_SHANG_MOD_MINGTIAO'),
			('CIVILIZATION_ERLITOU_MOD',		'TXT_KEY_CITY_NAME_XIA_SHANG_MOD_MUYE');

	UPDATE Leaders SET Description = 'TXT_KEY_LEADER_XIA_SHANG_WU_MOD_DESC' WHERE Type = 'LEADER_XIA_YU_MOD';
	UPDATE Leaders SET Civilopedia = 'TXT_KEY_LEADER_XIA_SHANG_WU_MOD_PEDIA' WHERE Type = 'LEADER_XIA_YU_MOD';
	UPDATE Leaders SET CivilopediaTag = 'TXT_KEY_LEADER_XIA_SHANG_WU_MOD' WHERE Type = 'LEADER_XIA_YU_MOD';

	DELETE FROM Diplomacy_Responses WHERE LeaderType IN ('LEADER_XIA_YU_MOD');
	INSERT INTO Diplomacy_Responses (LeaderType, ResponseType, Response, Bias) VALUES ('LEADER_XIA_YU_MOD',	'RESPONSE_FIRST_GREETING',	'TXT_KEY_LEADER_XIA_SHANG_WU_MOD_FIRST_GREETING_%','500');
	INSERT INTO Diplomacy_Responses (LeaderType, ResponseType, Response, Bias) VALUES ('LEADER_XIA_YU_MOD',	'RESPONSE_DEFEATED',		'TXT_KEY_LEADER_XIA_SHANG_WU_MOD_DEFEATED_%','500');
		
	UPDATE Traits SET Description = 'TXT_KEY_TRAIT_SHANG_DYNASTIC_CYCLE' WHERE Type = 'TRAIT_DYNASTIC_CYCLE';
	UPDATE Traits SET ShortDescription = 'TXT_KEY_TRAIT_SHANG_DYNASTIC_CYCLE_SHORT' WHERE Type = 'TRAIT_DYNASTIC_CYCLE';

	UPDATE Buildings SET Help = 'TXT_KEY_BUILDING_XIA_SHANG_MOD_BRONZE_WORKSHOP_HELP' WHERE Type = 'BUILDING_XIA_MOD_BRONZE_WOKRSHOP';
	UPDATE Buildings SET Strategy = 'TXT_KEY_BUILDING_XIA_SHANG_MOD_BRONZE_WORKSHOP_STRATEGY' WHERE Type = 'BUILDING_XIA_MOD_BRONZE_WOKRSHOP';
	UPDATE Buildings SET CultureRateModifier = 0 WHERE Type = 'BUILDING_XIA_RITUAL_BRONZE_DUMMY';
	UPDATE Buildings SET ReligiousPressureModifier = 25 WHERE Type = 'BUILDING_XIA_RITUAL_BRONZE_DUMMY';

	INSERT OR REPLACE INTO BuildingClasses 	
				(Type, 						 		 				DefaultBuilding, 								Description)
	VALUES		('BUILDINGCLASS_XIA_CHOPSTICK_DECISION_DUMMY', 		'BUILDING_XIA_CHOPSTICK_DECISION_DUMMY', 		'TXT_KEY_BUILDING_XIA_CHOPSTICK_DECISION_DUMMY_DESC');

	INSERT OR REPLACE INTO Buildings 	
				(Type, 						 					BuildingClass, 										Help,													Description, 											Civilopedia, 									Strategy,										GreatWorkCount,		Cost,		FaithCost,	PrereqTech, 	WorkerSpeedModifier,	ArtDefineTag,				MinAreaSize,	HurryCostModifier,	NeverCapture,	NukeImmune,		IconAtlas,		 PortraitIndex)
	VALUES		('BUILDING_XIA_CHOPSTICK_DECISION_DUMMY', 		'BUILDINGCLASS_XIA_CHOPSTICK_DECISION_DUMMY',		'TXT_KEY_BUILDING_XIA_CHOPSTICK_DECISION_DUMMY_HELP',	'TXT_KEY_BUILDING_XIA_CHOPSTICK_DECISION_DUMMY_DESC',	'TXT_KEY_BUILDING_XIA_DYNASTY_DUMMY_TEXT',		'TXT_KEY_BUILDING_XIA_DYNASTY_DUMMY_STRATEGY',	-1, 				-1,			-1, 		null,			20,						'ART_DEF_BUILDING_FORGE',	-1,				25,					1,				1,				'BW_ATLAS_1',				21);

	UPDATE Units SET Description = 'TXT_KEY_XIA_SHANG_GREAT_PERSON' WHERE Type = 'UNIT_DECISIONS_XIA_YU';

	INSERT INTO GreatWorks 

	INSERT INTO Building_YieldChanges 
			(BuildingType, 						YieldType, 			Yield)
	VALUES	('BUILDING_XIA_SHANG_SWITCH', 		'YIELD_CULTURE',		1);
