--Historical Religions
UPDATE Civilization_Religions SET ReligionType = 
	( CASE WHEN EXISTS(SELECT Type FROM Religions WHERE Type = 'RELIGION_HEROS_KARABAZMOS' )
		THEN 'RELIGION_HEROS_KARABAZMOS'
		ELSE ( CASE WHEN EXISTS(SELECT Type FROM Religions WHERE Type = 'RELIGION_ORTHODOXY' )
		THEN 'RELIGION_ORTHODOXY'
		ELSE 'RELIGION_CHRISTIANITY' END ) END
	) WHERE CivilizationType = 'CIVILIZATION_THRACE';

CREATE TRIGGER ReligionThraceSupportHeros
AFTER INSERT ON Religions WHEN 'RELIGION_HEROS_KARABAZMOS' = NEW.Type
BEGIN
	UPDATE Civilization_Religions 
	SET ReligionType = 'RELIGION_HEROS_KARABAZMOS'
	WHERE CivilizationType IN ('CIVILIZATION_THRACE');
END;