--==========================================================================================================================	
-- GreatWorks
--==========================================================================================================================	
INSERT INTO GreatWorks 
			(Type, 															GreatWorkClassType,			Description,														Quote,																		Audio,																Image)
VALUES		--Artists
			('GREAT_WORK_THE_CRUCIFIXTION_OF_SAINT_PETER', 					'GREAT_WORK_ART',			'TXT_KEY_GREAT_WORK_THE_CRUCIFIXTION_OF_SAINT_PETER',				null,																		'AS2D_DISCIPLE_ARTIST_WRITER',										'GW_Caravaggio--The_Crucifixtion_of_Saint_Peter.dds'),
			('GREAT_WORK_CORONATION_OF_THE_VIRGIN', 						'GREAT_WORK_ART',			'TXT_KEY_GREAT_WORK_CORONATION_OF_THE_VIRGIN',						null,																		'AS2D_DISCIPLE_ARTIST_WRITER',										'GW_Enguerrand_Quarton--Coronation_of_the_Virgin.dds'),
			('GREAT_WORK_THE_NUN', 											'GREAT_WORK_ART',			'TXT_KEY_GREAT_WORK_THE_NUN',										null,																		'AS2D_DISCIPLE_ARTIST_WRITER',										'GW_Gwen_John--The_Nun.dds'),
			('GREAT_WORK_PAINTING_OF_SAINT_DOMINIC', 						'GREAT_WORK_ART',			'TXT_KEY_GREAT_WORK_PAINTING_OF_ST_DOMINIC',						null,																		'AS2D_DISCIPLE_ARTIST_WRITER',										'GW_Fra_Angelico--St_Dominic.dds'),
			('GREAT_WORK_LAST_JUDGEMENT', 									'GREAT_WORK_ART',			'TXT_KEY_GREAT_WORK_LAST_JUDGEMENT',								null,																		'AS2D_DISCIPLE_ARTIST_WRITER',										'GW_Memling--Last_Judgement.dds'),
			('GREAT_WORK_MADONNA', 											'GREAT_WORK_ART',			'TXT_KEY_GREAT_WORK_MADONNA',										null,																		'AS2D_DISCIPLE_ARTIST_WRITER',										'GW_Raphael--Madonna.dds'),
			('GREAT_WORK_THE_ANNUNCIATION', 								'GREAT_WORK_ART',			'TXT_KEY_GREAT_WORK_THE_ANNUNCIATION',								null,																		'AS2D_DISCIPLE_ARTIST_WRITER',										'GW_Paolo_de_Matteis--The_Annunciation.dds'),
			('GREAT_WORK_MAN_OF_SORROWS', 									'GREAT_WORK_ART',			'TXT_KEY_GREAT_WORK_MAN_OF_SORROWS',								null,																		'AS2D_DISCIPLE_ARTIST_WRITER',										'GW_Man_of_Sorrows_Meister_Francke.dds'),
			('GREAT_WORK_LIBERATION_OF_SAINT_PETER', 						'GREAT_WORK_ART',			'TXT_KEY_GREAT_WORK_THE_LIBERATION_OF_SAINT_PETER',					null,																		'AS2D_DISCIPLE_ARTIST_WRITER',										'GW_Bartolomew_Esteban_Murillo--Liberation_of_St_Peter.dds'),
			('GREAT_WORK_SAINT_PETER_IN_PENITENCE', 						'GREAT_WORK_ART',			'TXT_KEY_GREAT_WORK_SAINT_PETER_IN_PENITENCE',						null,																		'AS2D_DISCIPLE_ARTIST_WRITER',										'GW_El_Greco--Saint_Peter_in_Penitence.dds'),
			('GREAT_WORK_LAMENTATION', 										'GREAT_WORK_ART',			'TXT_KEY_GREAT_WORK_LAMENTATION',									null,																		'AS2D_DISCIPLE_ARTIST_WRITER',										'GW_Scipione_Pulzone--Lamentation.dds'),
			('GREAT_WORK_FRESCO_OF_THE_LAST_JUDGEMENT', 					'GREAT_WORK_ART',			'TXT_KEY_GREAT_WORK_FRESCO_OF_THE_LAST_JUDGEMENT',					null,																		'AS2D_DISCIPLE_ARTIST_WRITER',										'GW_Michelangelo--Fresco_of_the_Last_Judgement.dds'),
			('GREAT_WORK_THE_STONING_OF_SAINT_STEPHEN', 					'GREAT_WORK_ART',			'TXT_KEY_GREAT_WORK_THE_STONING_OF_SAINT_STEPHEN',					null,																		'AS2D_DISCIPLE_ARTIST_WRITER',										'GW_Rembrant--The_Stoning_of_Saint_Stephen.dds'),
			('GREAT_WORK_ADORATION_OF_THE_MAGI', 							'GREAT_WORK_ART',			'TXT_KEY_GREAT_WORK_ADORATION_OF_THE_MAGI',							null,																		'AS2D_DISCIPLE_ARTIST_WRITER',										'GW_Rembrant--Adoration_of_the_Magi.dds'),
			('GREAT_WORK_MADONNA_OF_HUMILITY', 								'GREAT_WORK_ART',			'TXT_KEY_GREAT_WORK_MADONNA_OF_HUMILITY',							null,																		'AS2D_DISCIPLE_ARTIST_WRITER',										'GW_Fra_Angelico--Madonna_of_Humility.dds'),
			('GREAT_WORK_PAINTING_OF_SAINT_SEBASTIAN', 						'GREAT_WORK_ART',			'TXT_KEY_GREAT_WORK_PAINTING_OF_SAINT_SEBASTIAN',					null,																		'AS2D_DISCIPLE_ARTIST_WRITER',										'GW_Sandro_Botticellii--St.Sebastian.dds'),
			('GREAT_WORK_THE_WEDDING_AT_CANA', 								'GREAT_WORK_ART',			'TXT_KEY_GREAT_WORK_THE_WEDDING_AT_CANA',							null,																		'AS2D_DISCIPLE_ARTIST_WRITER',										'GW_Paolo_Veronese--The_Weddeding_at_Cana.dds'),
			('GREAT_WORK_IMMACULATE_CONCEPTION', 							'GREAT_WORK_ART',			'TXT_KEY_GREAT_WORK_IMMACULATE_CONCEPTION',							null,																		'AS2D_DISCIPLE_ARTIST_WRITER',										'GW_Murillo--Immaculate_Conception.dds'),
			--Musicians
			('GREAT_WORK_MISEREREI_MEI_DEUS', 								'GREAT_WORK_MUSIC',			'TXT_KEY_GREAT_WORK_MISEREREI_MEI_DEUS',							null,																		'AS2D_GREAT_MUSICIAN_ALLEGRIS_MISEREREI_MEI_DEUS',					'GreatMusician_Background.dds'),
			('GREAT_WORK_ALMA_REDEMPTORIS_MATER', 							'GREAT_WORK_MUSIC',			'TXT_KEY_GREAT_WORK_ALMA_REDEMPTORIS_MATER',						null,																		'AS2D_GREAT_MUSICIAN_PALESTRINAS_ALMA_REDEMPTORIS_MATER',			'GreatMusician_Background.dds'),
			('GREAT_WORK_MISSA_ET_ECCE_TERRAE_MOTUS_GLORIA',				'GREAT_WORK_MUSIC',			'TXT_KEY_GREAT_WORK_MISSA_ET_ECCE_TERRAE_MOTUS_GLORIA',				null,																		'AS2D_GREAT_MUSICIAN_BRUMELS_MISSA_ET_ECCE_TERRAE_MOTUS_GLORIA',	'GreatMusician_Background.dds'),
			('GREAT_WORK_MISSA_PAPAE_MARCELLI_CREDO', 						'GREAT_WORK_MUSIC',			'TXT_KEY_GREAT_WORK_MISSA_PAPAE_MARCELLI_CREDO',					null,																		'AS2D_GREAT_MUSICIAN_PALESTRINAS_MISSA_PAPAE_MARCELLI_CREDO',		'GreatMusician_Background.dds'),
			('GREAT_WORK_O_MORS_INEVITABILIS', 								'GREAT_WORK_MUSIC',			'TXT_KEY_GREAT_WORK_O_MORS_INEVITABILIS',							null,																		'AS2D_GREAT_MUSICIAN_VANDERS_O_MORS_INEVITABILIS',					'GreatMusician_Background.dds'),
			('GREAT_WORK_MEDIA_VITA', 										'GREAT_WORK_MUSIC',			'TXT_KEY_GREAT_WORK_MEDIA_VITA',									null,																		'AS2D_GREAT_MUSICIAN_SHEPPARDS_MEDIA_VITA',							'GreatMusician_Background.dds'),
			('GREAT_WORK_INTEMERATA', 										'GREAT_WORK_MUSIC',			'TXT_KEY_GREAT_WORK_INTEMERATA',									null,																		'AS2D_GREAT_MUSICIAN_OCKEGHEMS_INTEMERATA',							'GreatMusician_Background.dds'),
			('GREAT_WORK_AVE_MARIA', 										'GREAT_WORK_MUSIC',			'TXT_KEY_GREAT_WORK_AVE_MARIA',										null,																		'AS2D_GREAT_MUSICIAN_SCHUBERTS_AVE_MARIA',							'GreatMusician_Background.dds'),
			('GREAT_WORK_REQUIEM_DIES_IRAE', 								'GREAT_WORK_MUSIC',			'TXT_KEY_GREAT_WORK_REQUIEM_DIES_IRAE',								null,																		'AS2D_GREAT_MUSICIAN_VERDIS_REQUIEM',								'GreatMusician_Background.dds'),
			('GREAT_WORK_REQUIEM', 											'GREAT_WORK_MUSIC',			'TXT_KEY_GREAT_WORK_REQUIEM',										null,																		'AS2D_GREAT_MUSICIAN_MOZARTS_REQUIEM',								'GreatMusician_Background.dds'),
			--Writers
			('GREAT_WORK_HOW_TO_DRESS_FOR_EVERY_OCCASSION_BY_THE_POPE', 	'GREAT_WORK_LITERATURE',	'TXT_KEY_GREAT_WORK_HOW_TO_DRESS_FOR_EVERY_OCCASSION_BY_THE_POPE',	'TXT_KEY_GREAT_WORK_QUOTE_HOW_TO_DRESS_FOR_EVERY_OCCASSION_BY_THE_POPE',	'AS2D_DISCIPLE_ARTIST_WRITER',										'GreatWriter_Background.dds'),
			('GREAT_WORK_THE_SOULS_JOURNEY_TO_GOD', 						'GREAT_WORK_LITERATURE',	'TXT_KEY_GREAT_WORK_THE_SOULS_JOURNEY_TO_GOD',						'TXT_KEY_GREAT_WORK_QUOTE_THE_SOULS_JOURNEY_TO_GOD',						'AS2D_DISCIPLE_ARTIST_WRITER',										'GreatWriter_Background.dds'),
			('GREAT_WORK_THE_PRACTICE_OF_THE_PRESCENCE_OF_GOD', 			'GREAT_WORK_LITERATURE',	'TXT_KEY_GREAT_WORK_THE_PRACTICE_OF_THE_PRESCENCE_OF_GOD',			'TXT_KEY_GREAT_WORK_QUOTE_THE_PRACTICE_OF_THE_PRESCENCE_OF_GOD',			'AS2D_DISCIPLE_ARTIST_WRITER',										'GreatWriter_Background.dds'),
			('GREAT_WORK_THE_PARSONS_TALE', 								'GREAT_WORK_LITERATURE',	'TXT_KEY_GREAT_WORK_THE_PARSONS_TALE',								'TXT_KEY_GREAT_WORK_QUOTE_THE_PARSONS_TALE',								'AS2D_DISCIPLE_ARTIST_WRITER',										'GreatWriter_Background.dds'),
			('GREAT_WORK_THE_LETTERS_OF_SAINT_CATHERINE_OF_SIENA', 			'GREAT_WORK_LITERATURE',	'TXT_KEY_GREAT_WORK_THE_LETTERS_OF_SAINT_CATHERINE_OF_SIENA',		'TXT_KEY_GREAT_WORK_QUOTE_THE_LETTERS_OF_SAINT_CATHERINE_OF_SIENAE',		'AS2D_DISCIPLE_ARTIST_WRITER',										'GreatWriter_Background.dds'),
			('GREAT_WORK_THE_DIVINE_COMEDY', 								'GREAT_WORK_LITERATURE',	'TXT_KEY_GREAT_WORK_THE_DIVINE_COMEDY',								'TXT_KEY_GREAT_WORK_QUOTE_HE_DIVINE_COMEDY',								'AS2D_DISCIPLE_ARTIST_WRITER',										'GreatWriter_Background.dds'),
			('GREAT_WORK_THE_BETHROTHED', 									'GREAT_WORK_LITERATURE',	'TXT_KEY_GREAT_WORK_THE_BETHROTHED',								'TXT_KEY_GREAT_WORK_QUOTE_THE_BETHROTHED',									'AS2D_DISCIPLE_ARTIST_WRITER',										'GreatWriter_Background.dds'),
			('GREAT_WORK_THE_LIFE_OF_SAINT_TERESA_OF_AVILA_BY_HERSELF', 	'GREAT_WORK_LITERATURE',	'TXT_KEY_GREAT_WORK_THE_LIFE_OF_SAINT_TERESA_OF_AVILA_BY_HERSELF',	'TXT_KEY_GREAT_WORK_QUOTE_THE_LIFE_OF_SAINT_TERESA_OF_AVILA_BY_HERSELF',	'AS2D_DISCIPLE_ARTIST_WRITER',										'GreatWriter_Background.dds'),
			('GREAT_WORK_INTRODUCTION_TO_THE_DEVOUT_LIFE', 					'GREAT_WORK_LITERATURE',	'TXT_KEY_GREAT_WORK_INTRODUCTION_TO_THE_DEVOUT_LIFE',				'TXT_KEY_GREAT_WORK_QUOTE_INTRODUCTION_TO_THE_DEVOUT_LIFE',					'AS2D_DISCIPLE_ARTIST_WRITER',										'GreatWriter_Background.dds'),
			('GREAT_WORK_ASCENT_OF_MOUNT_CARMEL', 							'GREAT_WORK_LITERATURE',	'TXT_KEY_GREAT_WORK_ASCENT_OF_MOUNT_CARMEL',						'TXT_KEY_GREAT_WORK_QUOTE_ASCENT_OF_MOUNT_CARMEL',							'AS2D_DISCIPLE_ARTIST_WRITER',										'GreatWriter_Background.dds'),
			('GREAT_WORK_DIES_IRAE', 										'GREAT_WORK_LITERATURE',	'TXT_KEY_GREAT_WORK_DIES_IRAE',										'TXT_KEY_GREAT_WORK_QUOTE_DIES_IRAE',										'AS2D_DISCIPLE_ARTIST_WRITER',										'GreatWriter_Background.dds'),
			('GREAT_WORK_SUMMA_THEOLOGICA', 								'GREAT_WORK_LITERATURE',	'TXT_KEY_GREAT_WORK_SUMMA_THEOLOGICA',								'TXT_KEY_GREAT_WORK_QUOTE_SUMMA_THEOLOGICA',								'AS2D_DISCIPLE_ARTIST_WRITER',										'GreatWriter_Background.dds'),
			('GREAT_WORK_STORY_OF_A_SOUL', 									'GREAT_WORK_LITERATURE',	'TXT_KEY_GREAT_WORK_STORY_OF_A_SOUL',								'TXT_KEY_GREAT_WORK_QUOTE_STORY_OF_A_SOUL',									'AS2D_DISCIPLE_ARTIST_WRITER',										'GreatWriter_Background.dds'),
			('GREAT_WORK_THE_BOOK_OF_PASTORAL_RULE', 						'GREAT_WORK_LITERATURE',	'TXT_KEY_GREAT_WORK_THE_BOOK_OF_PASTORAL_RULE',						'TXT_KEY_GREAT_WORK_QUOTE_THE_BOOK_OF_PASTORAL_RULE',						'AS2D_DISCIPLE_ARTIST_WRITER',										'GreatWriter_Background.dds'),
			('GREAT_WORK_CITY_OF_GOD', 										'GREAT_WORK_LITERATURE',	'TXT_KEY_GREAT_WORK_CITY_OF_GOD',									'TXT_KEY_GREAT_WORK_QUOTE_CITY_OF_GOD',										'AS2D_DISCIPLE_ARTIST_WRITER',										'GreatWriter_Background.dds');
--==========================================================================================================================		
--==========================================================================================================================	
