--==========================================================================================================================	
-- Diplomacy_Responses
--==========================================================================================================================			
INSERT INTO Diplomacy_Responses 
			(LeaderType, 			ResponseType, 											Response, 																	Bias)
VALUES		('LEADER_GE_WILHELMII', 	'RESPONSE_FIRST_GREETING', 								'TXT_KEY_LEADER_GE_WILHELMII_FIRSTGREETING%', 									2),
			('LEADER_GE_WILHELMII', 	'RESPONSE_DEFEATED', 									'TXT_KEY_LEADER_GE_WILHELMII_DEFEATED%', 										2),	
			('LEADER_GE_WILHELMII', 	'RESPONSE_GREETING_REPEAT_TOO_MUCH', 					'TXT_KEY_LEADER_GE_WILHELMII_REPEAT_TOO_MUCH%', 								2),
			('LEADER_GE_WILHELMII', 	'RESPONSE_REPEAT_TRADE_TOO_MUCH', 						'TXT_KEY_LEADER_GE_WILHELMII_REPEAT_TRADE_TOO_MUCH%', 							2),
			('LEADER_GE_WILHELMII', 	'RESPONSE_GREETING_HOSTILE_REPEAT', 					'TXT_KEY_LEADER_GE_WILHELMII_REPEAT_TOO_MUCH%', 								2),
			('LEADER_GE_WILHELMII', 	'RESPONSE_GREETING_HOSTILE_HELLO', 						'TXT_KEY_LEADER_GE_WILHELMII_GREETING_HOSTILE_HELLO%', 						2),	
			('LEADER_GE_WILHELMII', 	'RESPONSE_GREETING_POLITE_HELLO', 						'TXT_KEY_LEADER_GE_WILHELMII_GREETING_POLITE_HELLO%', 							2),	
			('LEADER_GE_WILHELMII', 	'RESPONSE_GREETING_HOSTILE_HUMAN_SMALL_ARMY', 			'TXT_KEY_LEADER_GE_WILHELMII_GREETING_HOSTILE_HUMAN_SMALL_ARMY%', 				2),
			('LEADER_GE_WILHELMII', 	'RESPONSE_RESPONSE_TO_BEING_DENOUNCED', 				'TXT_KEY_LEADER_GE_WILHELMII_RESPONSE_TO_BEING_DENOUNCED%', 					2),
			('LEADER_GE_WILHELMII', 	'RESPONSE_WORK_AGAINST_SOMEONE', 						'TXT_KEY_LEADER_GE_WILHELMII_DENOUNCE%', 										2),
			('LEADER_GE_WILHELMII', 	'RESPONSE_AI_DOF_BACKSTAB', 							'TXT_KEY_LEADER_GE_WILHELMII_DENOUNCE%', 										2),
			('LEADER_GE_WILHELMII', 	'RESPONSE_RESPONSE_TO_BEING_DENOUNCED', 				'TXT_KEY_LEADER_GE_WILHELMII_RESPONSE_TO_BEING_DENOUNCED%', 					2),
			('LEADER_GE_WILHELMII', 	'RESPONSE_ATTACKED_HOSTILE', 							'TXT_KEY_LEADER_GE_WILHELMII_ATTACKED_HOSTILE%', 								2),
			('LEADER_GE_WILHELMII', 	'RESPONSE_ATTACKED_WEAK_HOSTILE', 						'TXT_KEY_LEADER_GE_WILHELMII_ATTACKED_HOSTILE%', 								2),
			('LEADER_GE_WILHELMII', 	'RESPONSE_ATTACKED_STRONG_HOSTILE', 					'TXT_KEY_LEADER_GE_WILHELMII_ATTACKED_HOSTILE%', 								2),
			('LEADER_GE_WILHELMII', 	'RESPONSE_ATTACKED_EXCITED', 							'TXT_KEY_LEADER_GE_WILHELMII_ATTACKED_EXCITED%', 								2),
			('LEADER_GE_WILHELMII', 	'RESPONSE_ATTACKED_WEAK_EXCITED', 						'TXT_KEY_LEADER_GE_WILHELMII_ATTACKED_EXCITED%', 								2),
			('LEADER_GE_WILHELMII', 	'RESPONSE_ATTACKED_STRONG_EXCITED', 					'TXT_KEY_LEADER_GE_WILHELMII_ATTACKED_EXCITED%', 								2),
			('LEADER_GE_WILHELMII', 	'RESPONSE_ATTACKED_SAD', 								'TXT_KEY_LEADER_GE_WILHELMII_ATTACKED_SAD%', 									2),
			('LEADER_GE_WILHELMII', 	'RESPONSE_ATTACKED_BETRAYED', 							'TXT_KEY_LEADER_GE_WILHELMII_ATTACKED_BETRAYED%', 								2),
			('LEADER_GE_WILHELMII', 	'RESPONSE_DOW_GENERIC', 								'TXT_KEY_LEADER_GE_WILHELMII_DOW_GENERIC%', 									2),
			('LEADER_GE_WILHELMII', 	'RESPONSE_DOW_LAND', 									'TXT_KEY_LEADER_GE_WILHELMII_DOW_LAND%', 										2),
			('LEADER_GE_WILHELMII', 	'RESPONSE_DOW_WORLD_CONQUEST', 							'TXT_KEY_LEADER_GE_WILHELMII_DOW_WORLD_CONQUEST%', 							2),
			('LEADER_GE_WILHELMII', 	'RESPONSE_DOW_OPPORTUNITY', 							'TXT_KEY_LEADER_GE_WILHELMII_DOW_OPPORTUNITY%', 								2),
			('LEADER_GE_WILHELMII', 	'RESPONSE_DOW_DESPERATE', 								'TXT_KEY_LEADER_GE_WILHELMII_DOW_DESPERATE%', 									2),
			('LEADER_GE_WILHELMII', 	'RESPONSE_TOO_SOON_NO_PEACE', 							'TXT_KEY_LEADER_GE_WILHELMII_TOO_SOON_NO_PEACE%', 								2);
--==========================================================================================================================			
--==========================================================================================================================						
