DELETE FROM Religions WHERE Type = 'RELIGION_BUDDHISM';
DELETE FROM Religions WHERE Type = 'RELIGION_CHRISTIANITY';
DELETE FROM Religions WHERE Type = 'RELIGION_CONFUCIANISM';
DELETE FROM Religions WHERE Type = 'RELIGION_HINDUISM';
DELETE FROM Religions WHERE Type = 'RELIGION_ISLAM';
DELETE FROM Religions WHERE Type = 'RELIGION_JUDAISM';
DELETE FROM Religions WHERE Type = 'RELIGION_SHINTO';
DELETE FROM Religions WHERE Type = 'RELIGION_SIKHISM';
DELETE FROM Religions WHERE Type = 'RELIGION_TAOISM';
DELETE FROM Religions WHERE Type = 'RELIGION_TENGRIISM';
DELETE FROM Religions WHERE Type = 'RELIGION_ZOROASTRIANISM';
DELETE FROM Religions WHERE Type = 'RELIGION_ORTHODOXY';
DELETE FROM Religions WHERE Type = 'RELIGION_PROTESTANTISM';

DELETE FROM Religions WHERE Type = 'RELIGION_CHRISTIAN_ARIANISM';
DELETE FROM Religions WHERE Type = 'RELIGION_CHRISTIAN_CHURCH_OF_THE_EAST';
DELETE FROM Religions WHERE Type = 'RELIGION_CHRISTIAN_ORIENTAL_ORTHODOX';
DELETE FROM Religions WHERE Type = 'RELIGION_CHRISTIAN_MORMONISM';

DELETE FROM Religions WHERE Type = 'RELIGION_CHRISTIAN_ANGLICANISM';
DELETE FROM Religions WHERE Type = 'RELIGION_PROTESTANT_CALVINISM';
DELETE FROM Religions WHERE Type = 'RELIGION_PROTESTANT_METHODISM';
DELETE FROM Religions WHERE Type = 'RELIGION_PROTESTANT_BAPTIST';

DELETE FROM Religions WHERE Type = 'RELIGION_MAHAYANA';
DELETE FROM Religions WHERE Type = 'RELIGION_VAJRAYANA';

DELETE FROM Religions WHERE Type = 'RELIGION_CHALDEANISM';
DELETE FROM Religions WHERE Type = 'RELIGION_SISKURMES';
DELETE FROM Religions WHERE Type = 'RELIGION_ASHURISM';
DELETE FROM Religions WHERE Type = 'RELIGION_NAPIRTUNIIS';

DELETE FROM Religions WHERE Type = 'RELIGION_HELLENISM';
DELETE FROM Religions WHERE Type = 'RELIGION_NUMENISM';
DELETE FROM Religions WHERE Type = 'RELIGION_IMPERIAL_CULT';
DELETE FROM Religions WHERE Type = 'RELIGION_MITHRAISM';
DELETE FROM Religions WHERE Type = 'RELIGION_NEOPLATONISM';
DELETE FROM Religions WHERE Type = 'RELIGION_HEROS_KARABAZMOS';

DELETE FROM Religions WHERE Type = 'RELIGION_VEDIC';
DELETE FROM Religions WHERE Type = 'RELIGION_VISHNU';
DELETE FROM Religions WHERE Type = 'RELIGION_SHIVA';
DELETE FROM Religions WHERE Type = 'RELIGION_SHAKTI';

DELETE FROM Religions WHERE Type = 'RELIGION_ISLAM_SHIA';
DELETE FROM Religions WHERE Type = 'RELIGION_ISLAM_IBADI';

DELETE FROM Religions WHERE Type = 'RELIGION_TLATEOMATILIZTLI';
DELETE FROM Religions WHERE Type = 'RELIGION_TZOLKIN';

DELETE FROM Religions WHERE Type = 'RELIGION_VODUN';
DELETE FROM Religions WHERE Type = 'RELIGION_SANTERIA';

DELETE FROM Religions WHERE Type = 'RELIGION_SLAVIANISM';
DELETE FROM Religions WHERE Type = 'RELIGION_ROMUVA';

DELETE FROM Religions WHERE Type = 'RELIGION_PESEDJET';
DELETE FROM Religions WHERE Type = 'RELIGION_ATENISM';
DELETE FROM Religions WHERE Type = 'RELIGION_AMANAIISM';

INSERT INTO Religions 
			(Type,												       					     Description,								     			Civilopedia,								  IconAtlas,	 PortraitIndex,		                                IconString)						   
VALUES	  --('RELIGION_CHRISTIANITY',							         'TXT_KEY_RELIGION_CHRISTIANITY',		              'TXT_KEY_RELIGION_CHRISTIANITY_PEDIA',					 'RELIGION_ATLAS_WHITE',				 1,					'[ICON_RELIGION_CHRISTIANITY]'),
		  ------
			('RELIGION_CHRISTIANITY',							 'TXT_KEY_RELIGION_CHRISTIAN_0_CATHOLIC',			  'TXT_KEY_RELIGION_CHRISTIAN_0_CATHOLIC_PEDIA',					 'RELIGION_ATLAS_WHITE',				 1,					'[ICON_RELIGION_CHRISTIANITY]'),
			('RELIGION_CHRISTIAN_ARIANISM',		        'TXT_KEY_RELIGION_CHRISTIAN_0_CATHOLIC_ARIANISM',	 'TXT_KEY_RELIGION_CHRISTIAN_0_CATHOLIC_ARIANISM_PEDIA',		'HISTORICAL_RELIGIONS_MASTER_ATLAS',				75,		 '[ICON_HISTORICAL_RELIGION_MOD_ARIANISM]'),
			('RELIGION_CHRISTIAN_CHURCH_OF_THE_EAST',			'TXT_KEY_RELIGION_CHRISTIAN_1_NESTORIAN',			 'TXT_KEY_RELIGION_CHRISTIAN_1_NESTORIAN_PEDIA',		'HISTORICAL_RELIGIONS_MASTER_ATLAS',			    43,		'[ICON_HISTORICAL_RELIGION_MOD_NESTORIAN]'),
			('RELIGION_CHRISTIAN_ORIENTAL_ORTHODOX',			   'TXT_KEY_RELIGION_CHRISTIAN_2_COPTIC',		        'TXT_KEY_RELIGION_CHRISTIAN_2_COPTIC_PEDIA',		'HISTORICAL_RELIGIONS_MASTER_ATLAS',			    17,		   '[ICON_HISTORICAL_RELIGION_MOD_COPTIC]'),
			('RELIGION_ORTHODOXY',								 'TXT_KEY_RELIGION_CHRISTIAN_3_ORTHODOX',		      'TXT_KEY_RELIGION_CHRISTIAN_3_ORTHODOX_PEDIA',					 'RELIGION_ATLAS_WHITE',			    12,						'[ICON_RELIGION_ORTHODOX]'),
			('RELIGION_CHRISTIAN_ANGLICANISM',					 'TXT_KEY_RELIGION_CHRISTIAN_4_ANGLICAN',		      'TXT_KEY_RELIGION_CHRISTIAN_4_ANGLICAN_PEDIA',		'HISTORICAL_RELIGIONS_MASTER_ATLAS',			    42,		 '[ICON_HISTORICAL_RELIGION_MOD_ANGLICAN]'),
		  --('RELIGION_PROTESTANTISM',							        'TXT_KEY_RELIGION_PROTESTANTISM',		             'TXT_KEY_RELIGION_PROTESTANTISM_PEDIA',				     'RELIGION_ATLAS_WHITE',			    13,				      '[ICON_RELIGION_PROTESTANT]'),
		  ------
			('RELIGION_PROTESTANTISM',							   'TXT_KEY_RELIGION_CHRISTIAN_5_LUTHER',		        'TXT_KEY_RELIGION_CHRISTIAN_5_LUTHER_PEDIA',				     'RELIGION_ATLAS_WHITE',			    13,				      '[ICON_RELIGION_PROTESTANT]'),
			('RELIGION_PROTESTANT_CALVINISM',					   'TXT_KEY_RELIGION_CHRISTIAN_6_CALVIN',		        'TXT_KEY_RELIGION_CHRISTIAN_6_CALVIN_PEDIA',		'HISTORICAL_RELIGIONS_MASTER_ATLAS',			    59,		   '[ICON_HISTORICAL_RELIGION_MOD_CALVIN]'),
			('RELIGION_PROTESTANT_METHODISM',				 	'TXT_KEY_RELIGION_CHRISTIAN_7_METHODIST',		     'TXT_KEY_RELIGION_CHRISTIAN_7_METHODIST_PEDIA',		'HISTORICAL_RELIGIONS_MASTER_ATLAS',			    63,		'[ICON_HISTORICAL_RELIGION_MOD_METHODIST]'),
			('RELIGION_PROTESTANT_BAPTIST',						  'TXT_KEY_RELIGION_CHRISTIAN_8_BAPTIST',		       'TXT_KEY_RELIGION_CHRISTIAN_8_BAPTIST_PEDIA',		'HISTORICAL_RELIGIONS_MASTER_ATLAS',			    64,		  '[ICON_HISTORICAL_RELIGION_MOD_BAPTIST]'),
			('RELIGION_CHRISTIAN_MORMONISM',				       'TXT_KEY_RELIGION_CHRISTIAN_9_MORMON',		        'TXT_KEY_RELIGION_CHRISTIAN_9_MORMON_PEDIA',		'HISTORICAL_RELIGIONS_MASTER_ATLAS',			    44,		   '[ICON_HISTORICAL_RELIGION_MOD_MORMON]'),
			('RELIGION_AKATTU',												   'TXT_KEY_RELIGION_AKATTU',					        'TXT_KEY_RELIGION_AKATTU_PEDIA',		'HISTORICAL_RELIGIONS_MASTER_ATLAS',			    61,		  '[ICON_HISTORICAL_RELIGION_MOD_HARAPPA]'),
			('RELIGION_AL_ASNAM',											 'TXT_KEY_RELIGION_AL_ASNAM',					      'TXT_KEY_RELIGION_AL_ASNAM_PEDIA',		'HISTORICAL_RELIGIONS_MASTER_ATLAS',			    48,		  '[ICON_HISTORICAL_RELIGION_MOD_SABAEAN]'),
			('RELIGION_AMATONGO',											 'TXT_KEY_RELIGION_AMATONGO',					      'TXT_KEY_RELIGION_AMATONGO_PEDIA',		'HISTORICAL_RELIGIONS_MASTER_ATLAS',			     1,		     '[ICON_HISTORICAL_RELIGION_MOD_ZULU]'),
			('RELIGION_ANGAKKUQISM',									  'TXT_KEY_RELIGION_ANGAKKUQISM',				       'TXT_KEY_RELIGION_ANGAKKUQISM_PEDIA',		'HISTORICAL_RELIGIONS_MASTER_ATLAS',			     5,		    '[ICON_HISTORICAL_RELIGION_MOD_INUIT]'),
			('RELIGION_BAHAI',													'TXT_KEY_RELIGION_BAHAI',				             'TXT_KEY_RELIGION_BAHAI_PEDIA',		'HISTORICAL_RELIGIONS_MASTER_ATLAS',			    62,		    '[ICON_HISTORICAL_RELIGION_MOD_BAHAI]'),
		  --('RELIGION_BUDDHISM',										     'TXT_KEY_RELIGION_BUDDHISM',		                  'TXT_KEY_RELIGION_BUDDHISM_PEDIA',					 'RELIGION_ATLAS_WHITE',				 0,					    '[ICON_RELIGION_BUDDHISM]'),
		  ------
			('RELIGION_BUDDHISM',								 'TXT_KEY_RELIGION_BUDDHIST_0_THERAVADA',		      'TXT_KEY_RELIGION_BUDDHIST_0_THERAVADA_PEDIA',					 'RELIGION_ATLAS_WHITE',				 0,					    '[ICON_RELIGION_BUDDHISM]'),
			('RELIGION_MAHAYANA',								  'TXT_KEY_RELIGION_BUDDHIST_1_MAHAYANA',		      'TXT_KEY_RELIGION_BUDDHIST_1_MAHAYANAI_PEDIA',		'HISTORICAL_RELIGIONS_MASTER_ATLAS',			    49,	     '[ICON_HISTORICAL_RELIGION_MOD_MAHAYANA]'),
			('RELIGION_VAJRAYANA',								 'TXT_KEY_RELIGION_BUDDHIST_2_VAJRAYANA',		      'TXT_KEY_RELIGION_BUDDHIST_2_VAJRAYANA_PEDIA',		'HISTORICAL_RELIGIONS_MASTER_ATLAS',			    50,		'[ICON_HISTORICAL_RELIGION_MOD_VAJRAYANA]'),
			('RELIGION_BUMUNTU',											  'TXT_KEY_RELIGION_BUMUNTU',		                   'TXT_KEY_RELIGION_BUMUNTU_PEDIA',		'HISTORICAL_RELIGIONS_MASTER_ATLAS',			    34,		     '[ICON_HISTORICAL_RELIGION_MOD_LUBA]'),
			('RELIGION_CANAANISM',										    'TXT_KEY_RELIGION_CANAANISM',		                 'TXT_KEY_RELIGION_CANAANISM_PEDIA',		'HISTORICAL_RELIGIONS_MASTER_ATLAS',			     4,		 '[ICON_HISTORICAL_RELIGION_MOD_CARTHAGE]'),
		  --('RELIGION_CHALDEANISM',									  'TXT_KEY_RELIGION_CHALDEANISM',		               'TXT_KEY_RELIGION_CHALDEANISM_PEDIA',		'HISTORICAL_RELIGIONS_MASTER_ATLAS',			    55,		  '[ICON_HISTORICAL_RELIGION_MOD_BABYLON]'),
		  ------
			--('RELIGION_SISKURMES',				    	      'TXT_KEY_RELIGION_CHALDEANISM_0_SUMER',		       'TXT_KEY_RELIGION_CHALDEANISM_0_SUMER_PEDIA',		'HISTORICAL_RELIGIONS_MASTER_ATLAS',			    54,		    '[ICON_HISTORICAL_RELIGION_MOD_SUMER]'),	
			('RELIGION_CHALDEANISM',						    'TXT_KEY_RELIGION_CHALDEANISM_1_BABYLON',		     'TXT_KEY_RELIGION_CHALDEANISM_1_BABYLON_PEDIA',		'HISTORICAL_RELIGIONS_MASTER_ATLAS',			    55,		  '[ICON_HISTORICAL_RELIGION_MOD_BABYLON]'),
			('RELIGION_ASHURISM',							    'TXT_KEY_RELIGION_CHALDEANISM_2_ASSYRIA',		     'TXT_KEY_RELIGION_CHALDEANISM_2_ASSYRIA_PEDIA',		'HISTORICAL_RELIGIONS_MASTER_ATLAS',			    60,		  '[ICON_HISTORICAL_RELIGION_MOD_ASSYRIA]'),
			('RELIGION_NAPIRTUNIIS',							   'TXT_KEY_RELIGION_CHALDEANISM_3_ELAM',		        'TXT_KEY_RELIGION_CHALDEANISM_3_ELAM_PEDIA',		'HISTORICAL_RELIGIONS_MASTER_ATLAS',			    74,		     '[ICON_HISTORICAL_RELIGION_MOD_ELAM]'),
			('RELIGION_CHIMINAGUA',										   'TXT_KEY_RELIGION_CHIMINAGUA',		                'TXT_KEY_RELIGION_CHIMINAGUA_PEDIA',		'HISTORICAL_RELIGIONS_MASTER_ATLAS',			    37,		   '[ICON_HISTORICAL_RELIGION_MOD_MUISCA]'),
			('RELIGION_CONFUCIANISM',									 'TXT_KEY_RELIGION_CONFUCIANISM',		              'TXT_KEY_RELIGION_CONFUCIANISM_PEDIA',					 'RELIGION_ATLAS_WHITE',				 2,					'[ICON_RELIGION_CONFUCIANISM]'),
			('RELIGION_DRUIDISM',											 'TXT_KEY_RELIGION_DRUIDISM',		                  'TXT_KEY_RELIGION_DRUIDISM_PEDIA',		'HISTORICAL_RELIGIONS_MASTER_ATLAS',			     0,		    '[ICON_HISTORICAL_RELIGION_MOD_CELTS]'),
			('RELIGION_FAT_ROOG',											 'TXT_KEY_RELIGION_FAT_ROOG',		                  'TXT_KEY_RELIGION_FAT_ROOG_PEDIA',		'HISTORICAL_RELIGIONS_MASTER_ATLAS',			    28,		    '[ICON_HISTORICAL_RELIGION_MOD_SERER]'),
			('RELIGION_FORN_SIDR',											'TXT_KEY_RELIGION_FORN_SIDR',		                 'TXT_KEY_RELIGION_FORN_SIDR_PEDIA',		'HISTORICAL_RELIGIONS_MASTER_ATLAS',			     2,		    '[ICON_HISTORICAL_RELIGION_MOD_NORSE]'),
			--('RELIGION_GNOSTICISM',									   'TXT_KEY_RELIGION_GNOSTICISM',		                'TXT_KEY_RELIGION_GNOSTICISM_PEDIA',		'HISTORICAL_RELIGIONS_MASTER_ATLAS',			    24,		  '[ICON_HISTORICAL_RELIGION_MOD_GNOSTIC]'),
		  --('RELIGION_HELLENISM',										    'TXT_KEY_RELIGION_HELLENISM',	                     'TXT_KEY_RELIGION_HELLENISM_PEDIA',		'HISTORICAL_RELIGIONS_MASTER_ATLAS',			     3,		   '[ICON_HISTORICAL_RELIGION_MOD_GREECE]'),
		  ------
			('RELIGION_HELLENISM',							 'TXT_KEY_RELIGION_HELLENISM_0_DODEKATHEISM',	      'TXT_KEY_RELIGION_HELLENISM_0_DODEKATHEISM_PEDIA',		'HISTORICAL_RELIGIONS_MASTER_ATLAS',			     3,		   '[ICON_HISTORICAL_RELIGION_MOD_GREECE]'),
			('RELIGION_NUMENISM',								 'TXT_KEY_RELIGION_HELLENISM_1_NUMENISM',	          'TXT_KEY_RELIGION_HELLENISM_1_NUMENISM_PEDIA',		'HISTORICAL_RELIGIONS_MASTER_ATLAS',			    45,		 '[ICON_HISTORICAL_RELIGION_MOD_NUMENISM]'),
			('RELIGION_IMPERIAL_CULT',						'TXT_KEY_RELIGION_HELLENISM_2_IMPERIAL_CULT',	     'TXT_KEY_RELIGION_HELLENISM_2_IMPERIAL_CULT_PEDIA',		'HISTORICAL_RELIGIONS_MASTER_ATLAS',			    72, '[ICON_HISTORICAL_RELIGION_MOD_IMPERIAL_CULT]'),
			('RELIGION_MITHRAISM',								'TXT_KEY_RELIGION_HELLENISM_3_MITHRAISM',		     'TXT_KEY_RELIGION_HELLENISM_3_MITHRAISM_PEDIA',		'HISTORICAL_RELIGIONS_MASTER_ATLAS',			    69,		  '[ICON_HISTORICAL_RELIGION_MOD_MITHRAS]'),
			('RELIGION_NEOPLATONISM',						 'TXT_KEY_RELIGION_HELLENISM_4_NEOPLATONISM',		  'TXT_KEY_RELIGION_HELLENISM_4_NEOPLATONISM_PEDIA',		'HISTORICAL_RELIGIONS_MASTER_ATLAS',			    71,  '[ICON_HISTORICAL_RELIGION_MOD_NEOPLATONISM]'),			
			('RELIGION_HEROS_KARABAZMOS',							'TXT_KEY_RELIGION_HELLENISM_5_HEROS',		         'TXT_KEY_RELIGION_HELLENISM_5_HEROS_PEDIA',		'HISTORICAL_RELIGIONS_MASTER_ATLAS',			    33,		   '[ICON_HISTORICAL_RELIGION_MOD_THRACE]'),	  		
			('RELIGION_HERMETICISM',							          'TXT_KEY_RELIGION_HERMETICISM',		               'TXT_KEY_RELIGION_HERMETICISM_PEDIA',		'HISTORICAL_RELIGIONS_MASTER_ATLAS',			    77,	  '[ICON_HISTORICAL_RELIGION_MOD_HERMETICISM]'),
		  --('RELIGION_HINDUISM',										     'TXT_KEY_RELIGION_HINDUISM',		                  'TXT_KEY_RELIGION_HINDUISM_PEDIA',					 'RELIGION_ATLAS_WHITE',			     3,						'[ICON_RELIGION_HINDUISM]'),
		  ------
			('RELIGION_VEDIC',										 'TXT_KEY_RELIGION_HINDUISM_0_VEDIC',		          'TXT_KEY_RELIGION_HINDUISM_0_VEDIC_PEDIA',		'HISTORICAL_RELIGIONS_MASTER_ATLAS',			    25,		    '[ICON_HISTORICAL_RELIGION_MOD_VEDIC]'),
			('RELIGION_VISHNU',										'TXT_KEY_RELIGION_HINDUISM_1_VISHNU',		         'TXT_KEY_RELIGION_HINDUISM_1_VISHNU_PEDIA',		'HISTORICAL_RELIGIONS_MASTER_ATLAS',			    46,		   '[ICON_HISTORICAL_RELIGION_MOD_VISHNU]'),
			('RELIGION_SHIVA',										 'TXT_KEY_RELIGION_HINDUISM_2_SHIVA',		          'TXT_KEY_RELIGION_HINDUISM_2_SHIVA_PEDIA',		'HISTORICAL_RELIGIONS_MASTER_ATLAS',			    40,		    '[ICON_HISTORICAL_RELIGION_MOD_SHIVA]'),
			('RELIGION_SHAKTI',										'TXT_KEY_RELIGION_HINDUISM_3_SHAKTI',		         'TXT_KEY_RELIGION_HINDUISM_3_SHAKTI_PEDIA',		'HISTORICAL_RELIGIONS_MASTER_ATLAS',			    47,		   '[ICON_HISTORICAL_RELIGION_MOD_SHAKTI]'),
			('RELIGION_HINDUISM',									'TXT_KEY_RELIGION_HINDUISM_4_SMARTA',		         'TXT_KEY_RELIGION_HINDUISM_4_SMARTA_PEDIA',					 'RELIGION_ATLAS_WHITE',			     3,						'[ICON_RELIGION_HINDUISM]'),
		  --('RELIGION_ISLAM',												    'TXT_KEY_RELIGION_ISLAM',				             'TXT_KEY_RELIGION_ISLAM_PEDIA',					 'RELIGION_ATLAS_WHITE',				 4,						   '[ICON_RELIGION_ISLAM]'),
		  ------
			('RELIGION_ISLAM',										    'TXT_KEY_RELIGION_ISLAM_0_SUNNI',				     'TXT_KEY_RELIGION_ISLAM_0_SUNNI_PEDIA',					 'RELIGION_ATLAS_WHITE',				 4,						   '[ICON_RELIGION_ISLAM]'),
			('RELIGION_ISLAM_SHIA',										 'TXT_KEY_RELIGION_ISLAM_1_SHIA',				      'TXT_KEY_RELIGION_ISLAM_1_SHIA_PEDIA',		'HISTORICAL_RELIGIONS_MASTER_ATLAS',			    51,		     '[ICON_HISTORICAL_RELIGION_MOD_SHIA]'),
			('RELIGION_ISLAM_IBADI',									'TXT_KEY_RELIGION_ISLAM_2_IBADI',				     'TXT_KEY_RELIGION_ISLAM_2_IBADI_PEDIA',		'HISTORICAL_RELIGIONS_MASTER_ATLAS',			    65,		     '[ICON_HISTORICAL_RELIGION_MOD_OMAN]'),
			('RELIGION_DRUZE',									        'TXT_KEY_RELIGION_ISLAM_3_DRUZE',				     'TXT_KEY_RELIGION_ISLAM_3_DRUZE_PEDIA',		'HISTORICAL_RELIGIONS_MASTER_ATLAS',			    68,		    '[ICON_HISTORICAL_RELIGION_MOD_DRUZE]'),			
			('RELIGION_ITAN',													 'TXT_KEY_RELIGION_ITAN',						      'TXT_KEY_RELIGION_ITAN_PEDIA',		'HISTORICAL_RELIGIONS_MASTER_ATLAS',			    13,		   '[ICON_HISTORICAL_RELIGION_MOD_YORUBA]'),
			('RELIGION_JAIN',													 'TXT_KEY_RELIGION_JAIN',						      'TXT_KEY_RELIGION_JAIN_PEDIA',		'HISTORICAL_RELIGIONS_MASTER_ATLAS',			    26,			 '[ICON_HISTORICAL_RELIGION_MOD_JAIN]'),
			('RELIGION_JUDAISM',											  'TXT_KEY_RELIGION_JUDAISM',					       'TXT_KEY_RELIGION_JUDAISM_PEDIA',					 'RELIGION_ATLAS_WHITE',				 5,						 '[ICON_RELIGION_JUDAISM]'),
			('RELIGION_KACHINA',											  'TXT_KEY_RELIGION_KACHINA',					       'TXT_KEY_RELIGION_KACHINA_PEDIA',		'HISTORICAL_RELIGIONS_MASTER_ATLAS',			    20,		   '[ICON_HISTORICAL_RELIGION_MOD_PUEBLO]'),
			('RELIGION_LAIBONI',											  'TXT_KEY_RELIGION_LAIBONI',					       'TXT_KEY_RELIGION_LAIBONI_PEDIA',		'HISTORICAL_RELIGIONS_MASTER_ATLAS',			    31,		   '[ICON_HISTORICAL_RELIGION_MOD_MAASAI]'),
			('RELIGION_LIIM_DINGERMES',								   'TXT_KEY_RELIGION_LIIM_DINGERMES',			        'TXT_KEY_RELIGION_LIIM_DINGERMES_PEDIA',		'HISTORICAL_RELIGIONS_MASTER_ATLAS',			    21,		  '[ICON_HISTORICAL_RELIGION_MOD_HITTITE]'),
			('RELIGION_MANAISM',											  'TXT_KEY_RELIGION_MANAISM',			               'TXT_KEY_RELIGION_MANAISM_PEDIA',		'HISTORICAL_RELIGIONS_MASTER_ATLAS',			     6,		'[ICON_HISTORICAL_RELIGION_MOD_POLYNESIA]'),
			('RELIGION_MANDEANISM',										   'TXT_KEY_RELIGION_MANDEANISM',			            'TXT_KEY_RELIGION_MANDEANISM_PEDIA',		'HISTORICAL_RELIGIONS_MASTER_ATLAS',			    41,		  '[ICON_HISTORICAL_RELIGION_MOD_MANDAEN]'),
			('RELIGION_MANICHAEISM',									  'TXT_KEY_RELIGION_MANICHAEISM',			           'TXT_KEY_RELIGION_MANICHAEISM_PEDIA',		'HISTORICAL_RELIGIONS_MASTER_ATLAS',			    10,		     '[ICON_HISTORICAL_RELIGION_MOD_MANI]'),
			('RELIGION_MIDEWIWIN',										    'TXT_KEY_RELIGION_MIDEWIWIN',			             'TXT_KEY_RELIGION_MIDEWIWIN_PEDIA',		'HISTORICAL_RELIGIONS_MASTER_ATLAS',			    12,		   '[ICON_HISTORICAL_RELIGION_MOD_OJIBWE]'),
			('RELIGION_MUISM',											   	    'TXT_KEY_RELIGION_MUISM',			                 'TXT_KEY_RELIGION_MUISM_PEDIA',		'HISTORICAL_RELIGIONS_MASTER_ATLAS',			    30,		    '[ICON_HISTORICAL_RELIGION_MOD_MUISM]'),
			('RELIGION_NOAIDEVUOHTA',									 'TXT_KEY_RELIGION_NOAIDEVUOHTA',			          'TXT_KEY_RELIGION_NOAIDEVUOHTA_PEDIA',		'HISTORICAL_RELIGIONS_MASTER_ATLAS',			    39,		     '[ICON_HISTORICAL_RELIGION_MOD_SAMI]'),
			('RELIGION_NUM',													  'TXT_KEY_RELIGION_NUM',			                   'TXT_KEY_RELIGION_NUM_PEDIA',		'HISTORICAL_RELIGIONS_MASTER_ATLAS',			    57,		  '[ICON_HISTORICAL_RELIGION_MOD_BUSHMEN]'),
			('RELIGION_NZAMBIISM',											'TXT_KEY_RELIGION_NZAMBIISM',			             'TXT_KEY_RELIGION_NZAMBIISM_PEDIA',		'HISTORICAL_RELIGIONS_MASTER_ATLAS',			     8,		    '[ICON_HISTORICAL_RELIGION_MOD_KONGO]'),
			('RELIGION_ONYAMESOM',											'TXT_KEY_RELIGION_ONYAMESOM',			             'TXT_KEY_RELIGION_ONYAMESOM_PEDIA',		'HISTORICAL_RELIGIONS_MASTER_ATLAS',			    56,		  '[ICON_HISTORICAL_RELIGION_MOD_ASHANTI]'),
			('RELIGION_ORENDA',												   'TXT_KEY_RELIGION_ORENDA',			                'TXT_KEY_RELIGION_ORENDA_PEDIA',		'HISTORICAL_RELIGIONS_MASTER_ATLAS',			    38,		 '[ICON_HISTORICAL_RELIGION_MOD_IROQUOIS]'),	
		  --('RELIGION_PACHISM',											  'TXT_KEY_RELIGION_PACHISM',			               'TXT_KEY_RELIGION_PACHISM_PEDIA',		'HISTORICAL_RELIGIONS_MASTER_ATLAS',			    18,		     '[ICON_HISTORICAL_RELIGION_MOD_INCA]'),
		  ------
			('RELIGION_PACHISM',								   'TXT_KEY_RELIGION_PACHISM_1_PACHAISM',			    'TXT_KEY_RELIGION_PACHISM_1_PACHAISM_PEDIA',		'HISTORICAL_RELIGIONS_MASTER_ATLAS',			    18,		     '[ICON_HISTORICAL_RELIGION_MOD_INCA]'),		
			('RELIGION_INTIISM',									'TXT_KEY_RELIGION_PACHISM_4_INTIISM',			     'TXT_KEY_RELIGION_PACHISM_4_INTIISM_PEDIA',		'HISTORICAL_RELIGIONS_MASTER_ATLAS',			    80,		  '[ICON_HISTORICAL_RELIGION_MOD_QUECHUA]'),
			('RELIGION_PAJELANCA',											'TXT_KEY_RELIGION_PAJELANCA',			             'TXT_KEY_RELIGION_PAJELANCA_PEDIA',		'HISTORICAL_RELIGIONS_MASTER_ATLAS',			     7,		     '[ICON_HISTORICAL_RELIGION_MOD_TUPI]'),
		  --('RELIGION_PESEDJET',											 'TXT_KEY_RELIGION_PESEDJET',			              'TXT_KEY_RELIGION_PESEDJET_PEDIA',		'HISTORICAL_RELIGIONS_MASTER_ATLAS',			    23,		    '[ICON_HISTORICAL_RELIGION_MOD_EGYPT]'),
		  ------
			('RELIGION_PESEDJET',									 'TXT_KEY_RELIGION_PESEDJET_0_EGYPT',			      'TXT_KEY_RELIGION_PESEDJET_0_EGYPT_PEDIA',		'HISTORICAL_RELIGIONS_MASTER_ATLAS',			    23,		    '[ICON_HISTORICAL_RELIGION_MOD_EGYPT]'),
			('RELIGION_ATENISM',								   'TXT_KEY_RELIGION_PESEDJET_1_ATENISM',		        'TXT_KEY_RELIGION_PESEDJET_1_ATENISM_PEDIA',		'HISTORICAL_RELIGIONS_MASTER_ATLAS',			    66,		  '[ICON_HISTORICAL_RELIGION_MOD_ATENISM]'),
			('RELIGION_AMANAIISM',								 'TXT_KEY_RELIGION_PESEDJET_2_AMANAIISM',		      'TXT_KEY_RELIGION_PESEDJET_2_AMANAIISM_PEDIA',		'HISTORICAL_RELIGIONS_MASTER_ATLAS',			    73,        '[ICON_HISTORICAL_RELIGION_MOD_BERBER]'),
			('RELIGION_POHAKANTENNA',									 'TXT_KEY_RELIGION_POHAKANTENNA',			          'TXT_KEY_RELIGION_POHAKANTENNA_PEDIA',		'HISTORICAL_RELIGIONS_MASTER_ATLAS',			    52,		 '[ICON_HISTORICAL_RELIGION_MOD_SHOSHONE]'),
			('RELIGION_RAZANA',												   'TXT_KEY_RELIGION_RAZANA',			                'TXT_KEY_RELIGION_RAZANA_PEDIA',		'HISTORICAL_RELIGIONS_MASTER_ATLAS',			    35,		 '[ICON_HISTORICAL_RELIGION_MOD_MALAGASY]'),
			('RELIGION_SAIRIMAISM',									       'TXT_KEY_RELIGION_SAIRIMAISM',			             'TXT_KEY_RELIGION_SAIRMAISM_PEDIA',		'HISTORICAL_RELIGIONS_MASTER_ATLAS',			    58,		  '[ICON_HISTORICAL_RELIGION_MOD_SCYTHIA]'),
			('RELIGION_SATSANA_PHI',								      'TXT_KEY_RELIGION_SATSANA_PHI',			           'TXT_KEY_RELIGION_SATSANA_PHI_PEDIA',		'HISTORICAL_RELIGIONS_MASTER_ATLAS',			    67,	  '[ICON_HISTORICAL_RELIGION_MOD_SATSANA_PHI]'),
			('RELIGION_SGAANAANG',									        'TXT_KEY_RELIGION_SGAANAANG',			             'TXT_KEY_RELIGION_SGAANAANG_PEDIA',		'HISTORICAL_RELIGIONS_MASTER_ATLAS',			    29,		    '[ICON_HISTORICAL_RELIGION_MOD_HAIDA]'),
			('RELIGION_SHINTO',										           'TXT_KEY_RELIGION_SHINTO',					        'TXT_KEY_RELIGION_SHINTO_PEDIA',					 'RELIGION_ATLAS_WHITE',				 6,						  '[ICON_RELIGION_SHINTO]'),
			('RELIGION_SIKHISM',										      'TXT_KEY_RELIGION_SIKHISM',					       'TXT_KEY_RELIGION_SIKHISM_PEDIA',					 'RELIGION_ATLAS_WHITE',				 7,						 '[ICON_RELIGION_SIKHISM]'),
		  --('RELIGION_SLAVIANISM',									       'TXT_KEY_RELIGION_SLAVIANISM',				        'TXT_KEY_RELIGION_SLAVIANISM_PEDIA',		'HISTORICAL_RELIGIONS_MASTER_ATLAS',			    22,		   '[ICON_HISTORICAL_RELIGION_MOD_SLAVIC]'),
		  ------			
			('RELIGION_SLAVIANISM',							  'TXT_KEY_RELIGION_SLAVIANISM_1_SLAVIANISM',		   'TXT_KEY_RELIGION_SLAVIANISM_1_SLAVIANISM_PEDIA',		'HISTORICAL_RELIGIONS_MASTER_ATLAS',			    22,		   '[ICON_HISTORICAL_RELIGION_MOD_SLAVIC]'),
			('RELIGION_ROMUVA',									  'TXT_KEY_RELIGION_SLAVIANISM_2_ROMUVA',			   'TXT_KEY_RELIGION_SLAVIANISM_2_ROMUVA_PEDIA',		'HISTORICAL_RELIGIONS_MASTER_ATLAS',			    36,		'[ICON_HISTORICAL_RELIGION_MOD_LITHUANIA]'),		
			('RELIGION_SOUTHERN_CULT',								    'TXT_KEY_RELIGION_SOUTHERN_CULT',			         'TXT_KEY_RELIGION_SOUTHERN_CULT_PEDIA',		'HISTORICAL_RELIGIONS_MASTER_ATLAS',			    15,	  '[ICON_HISTORICAL_RELIGION_MOD_MISSISSIPPI]'),		
			('RELIGION_TAOISM',										           'TXT_KEY_RELIGION_TAOISM',					        'TXT_KEY_RELIGION_TAOISM_PEDIA',					 'RELIGION_ATLAS_WHITE',				 8,						  '[ICON_RELIGION_TAOISM]'),
			('RELIGION_TENGRIISM',										    'TXT_KEY_RELIGION_TENGRIISM',					     'TXT_KEY_RELIGION_TENGRIISM_PEDIA',					 'RELIGION_ATLAS_WHITE',				 9,					   '[ICON_RELIGION_TENGRIISM]'),		
			('RELIGION_TJUKURPA',								             'TXT_KEY_RELIGION_TJUKURPA',			              'TXT_KEY_RELIGION_TJUKURPA_PEDIA',		'HISTORICAL_RELIGIONS_MASTER_ATLAS',		 	    70,	    '[ICON_HISTORICAL_RELIGION_MOD_ABORIGINE]'),		 
		  --('RELIGION_TLATEOMATILIZTLI',						     'TXT_KEY_RELIGION_TLATEOMATILIZTLI',			      'TXT_KEY_RELIGION_TLATEOMATILIZTLI_PEDIA',		'HISTORICAL_RELIGIONS_MASTER_ATLAS',		 	    19,	        '[ICON_HISTORICAL_RELIGION_MOD_AZTEC]'),	
		  ------
			('RELIGION_TLATEOMATILIZTLI',					 'TXT_KEY_RELIGION_TLATEOMATILIZTLI_1_AZTEC',		  'TXT_KEY_RELIGION_TLATEOMATILIZTLI_1_AZTEC_PEDIA',		'HISTORICAL_RELIGIONS_MASTER_ATLAS',		 	    19,	        '[ICON_HISTORICAL_RELIGION_MOD_AZTEC]'),
			('RELIGION_TZOLKIN',					          'TXT_KEY_RELIGION_TLATEOMATILIZTLI_2_MAYA',		   'TXT_KEY_RELIGION_TLATEOMATILIZTLI_2_MAYA_PEDIA',		'HISTORICAL_RELIGIONS_MASTER_ATLAS',		 	    78,	         '[ICON_HISTORICAL_RELIGION_MOD_MAYA]'),					
		  --('RELIGION_VODUN',									                'TXT_KEY_RELIGION_VODUN',			                 'TXT_KEY_RELIGION_VODUN_PEDIA',		'HISTORICAL_RELIGIONS_MASTER_ATLAS',		 	    14,	       '[ICON_HISTORICAL_RELIGION_MOD_VOODOO]'),					
		  ------
			('RELIGION_VODUN',									       'TXT_KEY_RELIGION_VODUN_0_VOODOO',			        'TXT_KEY_RELIGION_VODUN_0_VOODOO_PEDIA',		'HISTORICAL_RELIGIONS_MASTER_ATLAS',		 	    14,	       '[ICON_HISTORICAL_RELIGION_MOD_VOODOO]'),	
			('RELIGION_SANTERIA',									 'TXT_KEY_RELIGION_VODUN_1_SANTERIA',			      'TXT_KEY_RELIGION_VODUN_1_SANTERIA_PEDIA',		'HISTORICAL_RELIGIONS_MASTER_ATLAS',		 	    76,	     '[ICON_HISTORICAL_RELIGION_MOD_SANTERIA]'),	
			('RELIGION_WAKAN_TANKA',								      'TXT_KEY_RELIGION_WAKAN_TANKA',			           'TXT_KEY_RELIGION_WAKAN_TANKA_PEDIA',		'HISTORICAL_RELIGIONS_MASTER_ATLAS',		 	    11,	        '[ICON_HISTORICAL_RELIGION_MOD_SIOUX]'),
			('RELIGION_WILTRAN_MAPU',								     'TXT_KEY_RELIGION_WILTRAN_MAPU',			          'TXT_KEY_RELIGION_WILTRAN_MAPU_PEDIA',		'HISTORICAL_RELIGIONS_MASTER_ATLAS',		 	    53,	      '[ICON_HISTORICAL_RELIGION_MOD_MAPUCHE]'),
			('RELIGION_YAZDANISM',									        'TXT_KEY_RELIGION_YAZDANISM',			             'TXT_KEY_RELIGION_YAZDANISM_PEDIA',		'HISTORICAL_RELIGIONS_MASTER_ATLAS',		 	    27,	        '[ICON_HISTORICAL_RELIGION_MOD_KURDS]'),
			('RELIGION_ZEMIISM',									             'TXT_KEY_RELIGION_ZEMI',			                  'TXT_KEY_RELIGION_ZEMI_PEDIA',		'HISTORICAL_RELIGIONS_MASTER_ATLAS',		 	    32,	        '[ICON_HISTORICAL_RELIGION_MOD_TAINO]'),
			('RELIGION_ZOROASTRIANISM',							       'TXT_KEY_RELIGION_ZOROASTRIANISM',			        'TXT_KEY_RELIGION_ZOROASTRIANISM_PEDIA',					 'RELIGION_ATLAS_WHITE',				10,				  '[ICON_RELIGION_ZOROASTRIANISM]');

UPDATE Religions SET PortraitIndex =
	( CASE WHEN EXISTS(SELECT Type FROM Civilizations WHERE Type='CIVILIZATION_OMAN' )
		THEN "16"
		ELSE "65" END
	) WHERE Type = 'RELIGION_ISLAM_IBADI';

UPDATE Religions SET IconString =
	( CASE WHEN EXISTS(SELECT Type FROM Civilizations WHERE Type='CIVILIZATION_OMAN' )
		THEN "[ICON_HISTORICAL_RELIGION_MOD_IBADI]"
		ELSE "[ICON_HISTORICAL_RELIGION_MOD_OMAN]" END
	) WHERE Type = 'RELIGION_ISLAM_IBADI';

CREATE TRIGGER CivilizationOmanArtOne
AFTER INSERT ON Civilizations WHEN 'CIVILIZATION_OMAN' = NEW.Type
BEGIN
	UPDATE Religions SET PortraitIndex =
		( CASE WHEN EXISTS(SELECT Type FROM Civilizations WHERE Type='CIVILIZATION_OMAN' )
			THEN "16"
			ELSE "65" END
	   ) WHERE Type = 'RELIGION_ISLAM_IBADI';
END;

CREATE TRIGGER CivilizationOmanArtTwo
AFTER INSERT ON Civilizations WHEN 'CIVILIZATION_OMAN' = NEW.Type
BEGIN
	UPDATE Religions SET IconString =
		( CASE WHEN EXISTS(SELECT Type FROM Civilizations WHERE Type='CIVILIZATION_OMAN' )
			THEN "[ICON_HISTORICAL_RELIGION_MOD_IBADI]"
			ELSE "[ICON_HISTORICAL_RELIGION_MOD_OMAN]" END
		) WHERE Type = 'RELIGION_ISLAM_IBADI';
END;

DELETE FROM Religions WHERE Type = 'RELIGION_AKAN';

CREATE TRIGGER StrangeReligionsOverlap
AFTER INSERT ON Religions WHEN 'RELIGION_PASTA' = NEW.Type
BEGIN
	DELETE FROM Religions WHERE Type = 'RELIGION_AKAN';
END;