UPDATE Civilization_Religions SET ReligionType = 
	( CASE WHEN EXISTS(SELECT Type FROM Religions WHERE Type="RELIGION_SANTERIA" )
		THEN "RELIGION_SANTERIA"
		ELSE ( CASE WHEN EXISTS(SELECT Type FROM Religions WHERE Type="RELIGION_ITAN" )
		THEN "RELIGION_ITAN"
		ELSE "RELIGION_CHRISTIANITY" END
	)" END
	) WHERE CivilizationType = "CIVILIZATION_LEUGI_CUBA";


