--==========================================================================================================================
-- Unit_UniqueNames
--==========================================================================================================================
INSERT INTO Unit_UniqueNames 
			(UnitType, 				UniqueName,													GreatWorkType)
VALUES		--Rune Singers
			('UNIT_FINNIC_RUNE_SINGER', 	'TXT_KEY_GREAT_PERSON_RUNE_SINGER_DESC_1',		'GREAT_WORK_BIRTH_OF_WAINAMOINEN'), --BW
			('UNIT_FINNIC_RUNE_SINGER', 	'TXT_KEY_GREAT_PERSON_RUNE_SINGER_DESC_2',		'GREAT_WORK_WAINAMOINENS_SOWING'), --WS
			('UNIT_FINNIC_RUNE_SINGER', 	'TXT_KEY_GREAT_PERSON_RUNE_SINGER_DESC_3',		'GREAT_WORK_JOUKAHAINEN'), --J
			('UNIT_FINNIC_RUNE_SINGER', 	'TXT_KEY_GREAT_PERSON_RUNE_SINGER_DESC_4',		'GREAT_WORK_AINO_AND_THE_WATER-MAIDENS'), --AWM
			('UNIT_FINNIC_RUNE_SINGER', 	'TXT_KEY_GREAT_PERSON_RUNE_SINGER_DESC_5',		'GREAT_WORK_ORIGIN_OF_IRON'), --OI
			('UNIT_FINNIC_RUNE_SINGER', 	'TXT_KEY_GREAT_PERSON_RUNE_SINGER_DESC_6',		'GREAT_WORK_ILMARINEN'), --I
			('UNIT_FINNIC_RUNE_SINGER', 	'TXT_KEY_GREAT_PERSON_RUNE_SINGER_DESC_7',		'GREAT_WORK_ILMARINEN_FORGES_THE_SAMPO'), --IFS
			('UNIT_FINNIC_RUNE_SINGER', 	'TXT_KEY_GREAT_PERSON_RUNE_SINGER_DESC_8',		'GREAT_WORK_LEMMINKAINENS_RESTORATION'), --LR
			('UNIT_FINNIC_RUNE_SINGER', 	'TXT_KEY_GREAT_PERSON_RUNE_SINGER_DESC_9',		'GREAT_WORK_WAINAMOINENS_BOAT-BUILDING'), --WBB
			('UNIT_FINNIC_RUNE_SINGER', 	'TXT_KEY_GREAT_PERSON_RUNE_SINGER_DESC_10',		'GREAT_WORK_THE_BREWING_OF_BEER'), --BB
			('UNIT_FINNIC_RUNE_SINGER', 	'TXT_KEY_GREAT_PERSON_RUNE_SINGER_DESC_11',		'GREAT_WORK_WAINAMOINENS_HARP'), --WH
			('UNIT_FINNIC_RUNE_SINGER', 	'TXT_KEY_GREAT_PERSON_RUNE_SINGER_DESC_12',		'GREAT_WORK_LOUHI_SUMMONS_THE_SEA-MONSTER'), --LSSS
			('UNIT_FINNIC_RUNE_SINGER', 	'TXT_KEY_GREAT_PERSON_RUNE_SINGER_DESC_13',		'GREAT_WORK_FRAGMENTING_OF_THE_SAMPO'), --FS
			('UNIT_FINNIC_RUNE_SINGER', 	'TXT_KEY_GREAT_PERSON_RUNE_SINGER_DESC_14',		'GREAT_WORK_LOUHI_STEALS_SUN_MOON_AND_FIRE'), --LS
			('UNIT_FINNIC_RUNE_SINGER', 	'TXT_KEY_GREAT_PERSON_RUNE_SINGER_DESC_15',		'GREAT_WORK_KULLERVOS_EVIL_DEEDS'), --KED
			('UNIT_FINNIC_RUNE_SINGER', 	'TXT_KEY_GREAT_PERSON_RUNE_SINGER_DESC_16',		'GREAT_WORK_WAINAMOINENS_DEPARTURE'); --WD
--==========================================================================================================================
--==========================================================================================================================		
		
			