-- Insert SQL Rules Here 
INSERT INTO Improvement_ResourceTypes	(ImprovementType,			ResourceType,			ResourceMakesValid, ResourceTrade,	DiscoveryRand,	QuantityRequirement) VALUES
										('IMPROVEMENT_MINE',		'RESOURCE_CLAY',		1,					1,				0,				0),
										('IMPROVEMENT_MINE',		'RESOURCE_LEAD',		1,					1,				0,				0),
										('IMPROVEMENT_MINE',		'RESOURCE_NICKLE',		1,					1,				0,				0),
										('IMPROVEMENT_MINE',		'RESOURCE_PLATINUM',	1,					1,				0,				0),
										('IMPROVEMENT_MINE',		'RESOURCE_RUBY',		1,					1,				0,				0),
										('IMPROVEMENT_MINE',		'RESOURCE_SAPPHIRE',	1,					1,				0,				0),
										('IMPROVEMENT_MINE',		'RESOURCE_EMERALD',		1,					1,				0,				0),
										('IMPROVEMENT_MINE',		'RESOURCE_JADE',		1,					1,				0,				0),
										('IMPROVEMENT_PLANTATION',	'RESOURCE_BLUEBERRY',	1,					1,				0,				0),
										('IMPROVEMENT_PLANTATION',	'RESOURCE_PEANUT',		1,					1,				0,				0),
										('IMPROVEMENT_PLANTATION',	'RESOURCE_PINEAPPLE',	1,					1,				0,				0),
										('IMPROVEMENT_PLANTATION',	'RESOURCE_SUNFLOWER',	1,					1,				0,				0),
										('IMPROVEMENT_PLANTATION',	'RESOURCE_LAVENDER',	1,					1,				0,				0),
										('IMPROVEMENT_PLANTATION',	'RESOURCE_SOYBEAN',		1,					1,				0,				0),
										('IMPROVEMENT_PLANTATION',	'RESOURCE_COCONUT',		1,					1,				0,				0),
										('IMPROVEMENT_PLANTATION',	'RESOURCE_RUBBER',		1,					1,				0,				0),
										('IMPROVEMENT_PLANTATION',	'RESOURCE_TEA',			1,					1,				0,				0),
										('IMPROVEMENT_PLANTATION',	'RESOURCE_APPLE',		1,					1,				0,				0),
										('IMPROVEMENT_LUMBERMILL',	'RESOURCE_MAHOGANY',	1,					1,				0,				0),
										('IMPROVEMENT_LUMBERMILL',	'RESOURCE_PINE',		1,					1,				0,				0),
										('IMPROVEMENT_PLANTATION',	'RESOURCE_COFFEE',		1,					1,				0,				0),
										('IMPROVEMENT_MINE',		'RESOURCE_TITANIUM',	1,					1,				0,				0),
										('IMPROVEMENT_PLANTATION',	'RESOURCE_ALOE_VERA',	1,					1,				0,				0),
										('IMPROVEMENT_PLANTATION',	'RESOURCE_POPPY',		1,					1,				0,				0),
										('IMPROVEMENT_MINE',		'RESOURCE_MANGANESE',	1,					1,				0,				0),
										('IMPROVEMENT_MINE',		'RESOURCE_AMBER',		1,					1,				0,				0),
										('IMPROVEMENT_MINE',		'RESOURCE_TIN',			1,					1,				0,				0),
										('IMPROVEMENT_PLANTATION',	'RESOURCE_FLAX',		1,					1,				0,				0),
										('IMPROVEMENT_PLANTATION',	'RESOURCE_TOBACCO',		1,					1,				0,				0),
										('IMPROVEMENT_FARM',		'RESOURCE_OATS',		1,					1,				0,				0),
										('IMPROVEMENT_FARM',		'RESOURCE_HOPS',		1,					1,				0,				0),
										('IMPROVEMENT_FARM',		'RESOURCE_POTATOE',		1,					1,				0,				0),
										('IMPROVEMENT_FARM',		'RESOURCE_CORN',		1,					1,				0,				0),
										('IMPROVEMENT_FARM',		'RESOURCE_BARLEY',		1,					1,				0,				0),
										('IMPROVEMENT_PLANTATION',	'RESOURCE_MANGO',		1,					1,				0,				0);
-- Debug
INSERT INTO HNRDebugTableCheck(Num, FileName) VALUES (17, 'Improvement_ResourceTypes.sql');	
