-- Insert SQL Rules Here 
INSERT INTO Building_ResourceYieldChanges	(BuildingType,				ResourceType,				YieldType,				Yield) VALUES
											('BUILDING_BAZAAR',			'RESOURCE_MANGO',			'YIELD_GOLD',			1),
											('BUILDING_BAZAAR',			'RESOURCE_TEA',				'YIELD_GOLD',			1),
											('BUILDING_BAZAAR',			'RESOURCE_COFFEE',			'YIELD_GOLD',			1),
											('BUILDING_BAZAAR',			'RESOURCE_TOBACCO',			'YIELD_GOLD',			1),
											('BUILDING_BAZAAR',			'RESOURCE_CACAO',			'YIELD_GOLD',			1),
											('BUILDING_MINT',			'RESOURCE_SAPPHIRE',		'YIELD_GOLD',			2),
											('BUILDING_MINT',			'RESOURCE_RUBY',			'YIELD_GOLD',			2),
											('BUILDING_MINT',			'RESOURCE_EMERALD',			'YIELD_GOLD',			2),
											('BUILDING_CASTLE',			'RESOURCE_POTATOE',			'YIELD_FOOD',			1),
											('BUILDING_CASTLE',			'RESOURCE_OATS',			'YIELD_FOOD',			1),
											('BUILDING_HARBOR',			'RESOURCE_PINEAPPLE',		'YIELD_FOOD',			1),
											('BUILDING_HARBOR',			'RESOURCE_SOYBEAN',			'YIELD_FOOD',			1),
											('BUILDING_HARBOR',			'RESOURCE_PEANUT',			'YIELD_FOOD',			1),
											('BUILDING_MONASTERY',		'RESOURCE_LAVENDER',		'YIELD_CULTURE',		1),
											('BUILDING_MONASTERY',		'RESOURCE_HOPS',			'YIELD_CULTURE',		1),
											('BUILDING_GARDEN',			'RESOURCE_SUNFLOWER',		'YIELD_FOOD',			1),
											('BUILDING_GARDEN',			'RESOURCE_BLUEBERRY',		'YIELD_FOOD',			1),
											('BUILDING_GARDEN',			'RESOURCE_APPLE',			'YIELD_FOOD',			1),
											('BUILDING_TEMPLE',			'RESOURCE_ALOE_VERA',		'YIELD_GOLD',			1),
											('BUILDING_AMPHITHEATER',	'RESOURCE_FLAX',			'YIELD_CULTURE',		1),
											('BUILDING_FACTORY',		'RESOURCE_TITANIUM',		'YIELD_PRODUCTION',		2),
											('BUILDING_FACTORY',		'RESOURCE_PLATINUM',		'YIELD_GOLD',			2),
											('BUILDING_FORGE',			'RESOURCE_TIN',				'YIELD_PRODUCTION',		1),
											('BUILDING_FORGE',			'RESOURCE_MANGANESE',		'YIELD_PRODUCTION',		1),
											('BUILDING_FORGE',			'RESOURCE_NICKLE',			'YIELD_PRODUCTION',		1),
											('BUILDING_FORGE',			'RESOURCE_LEAD',			'YIELD_PRODUCTION',		1),
											('BUILDING_GRANARY',		'RESOURCE_BARLEY',			'YIELD_FOOD',			1),
											('BUILDING_MARKET',			'RESOURCE_MANGO',			'YIELD_GOLD',			1),
											('BUILDING_MARKET',			'RESOURCE_TEA',				'YIELD_GOLD',			1),
											('BUILDING_MARKET',			'RESOURCE_COFFEE',			'YIELD_GOLD',			1),
											('BUILDING_MARKET',			'RESOURCE_TOBACCO',			'YIELD_GOLD',			1),
											('BUILDING_GRANARY',		'RESOURCE_CORN',			'YIELD_FOOD',			1);
-- Debug
INSERT INTO HNRDebugTableCheck(Num, FileName) VALUES (9, 'Update Buildings.sql');	