--==========================================================================================================================
-- DecisionsAddin_Support
--==========================================================================================================================
INSERT INTO DecisionsAddin_Support (FileName) VALUES ('TCM_IberianDecisions.lua');
--==========================================================================================================================
-- Policies
--==========================================================================================================================
			INSERT INTO Policies 
			(Type, 						Description)
VALUES		('POLICY_TCM_TOLEDO_STEEL', 	'TXT_KEY_DECISIONS_TCM_THE_IBERIANS_TOLEDO_STEEL'),
			('POLICY_TCM_IBERIAN_BONUS_1', 	'TXT_KEY_DECISIONS_IBERIANSCULPTURE'),
			('POLICY_TCM_IBERIAN_BONUS_2', 	'TXT_KEY_DECISIONS_IBERIANSCULPTURE'),
			('POLICY_TCM_IBERIAN_BONUS_3', 	'TXT_KEY_DECISIONS_IBERIANSCULPTURE'),
			('POLICY_TCM_IBERIAN_BONUS_4', 	'TXT_KEY_DECISIONS_IBERIANSCULPTURE'),
			('POLICY_TCM_IBERIAN_BONUS_5', 	'TXT_KEY_DECISIONS_IBERIANSCULPTURE'),
			('POLICY_TCM_IBERIAN_BONUS_6', 	'TXT_KEY_DECISIONS_IBERIANSCULPTURE'),
			('POLICY_TCM_IBERIAN_BONUS_7', 	'TXT_KEY_DECISIONS_IBERIANSCULPTURE'),
			('POLICY_TCM_IBERIAN_BONUS_8', 	'TXT_KEY_DECISIONS_IBERIANSCULPTURE'),
			('POLICY_TCM_IBERIAN_BONUS_9', 	'TXT_KEY_DECISIONS_IBERIANSCULPTURE'),
			('POLICY_TCM_IBERIAN_BONUS_10', 	'TXT_KEY_DECISIONS_IBERIANSCULPTURE'),
			('POLICY_TCM_IBERIAN_BONUS_11', 	'TXT_KEY_DECISIONS_IBERIANSCULPTURE'),
			('POLICY_TCM_IBERIAN_BONUS_12', 	'TXT_KEY_DECISIONS_IBERIANSCULPTURE'),
			('POLICY_TCM_IBERIAN_BONUS_13', 	'TXT_KEY_DECISIONS_IBERIANSCULPTURE'),
			('POLICY_TCM_IBERIAN_BONUS_14', 	'TXT_KEY_DECISIONS_IBERIANSCULPTURE'),
			('POLICY_TCM_IBERIAN_BONUS_15', 	'TXT_KEY_DECISIONS_IBERIANSCULPTURE');

			INSERT INTO Policy_BuildingClassYieldChanges 
			(PolicyType, 			       BuildingClassType,           YieldType,	    YieldChange)
VALUES		('POLICY_TCM_IBERIAN_BONUS_1', 'BUILDINGCLASS_STONE_WORKS', 'YIELD_CULTURE', 2),
			('POLICY_TCM_IBERIAN_BONUS_3', 'BUILDINGCLASS_STONE_WORKS', 'YIELD_PRODUCTION', 1),
			('POLICY_TCM_IBERIAN_BONUS_6', 'BUILDINGCLASS_STONE_WORKS', 'YIELD_GOLD', 2),
			('POLICY_TCM_IBERIAN_BONUS_7', 'BUILDINGCLASS_STONE_WORKS', 'YIELD_GOLD', 1),
			('POLICY_TCM_IBERIAN_BONUS_7', 'BUILDINGCLASS_STONE_WORKS', 'YIELD_CULTURE', 1),
			('POLICY_TCM_IBERIAN_BONUS_8', 'BUILDINGCLASS_STONE_WORKS', 'YIELD_CULTURE', 3),
			('POLICY_TCM_IBERIAN_BONUS_9', 'BUILDINGCLASS_STONE_WORKS', 'YIELD_PRODUCTION', 2),
			('POLICY_TCM_IBERIAN_BONUS_12', 'BUILDINGCLASS_STONE_WORKS', 'YIELD_CULTURE', 2),
			('POLICY_TCM_IBERIAN_BONUS_12', 'BUILDINGCLASS_STONE_WORKS', 'YIELD_PRODUCTION', 1),
			('POLICY_TCM_IBERIAN_BONUS_13', 'BUILDINGCLASS_STONE_WORKS', 'YIELD_FOOD', 1),
			('POLICY_TCM_IBERIAN_BONUS_13', 'BUILDINGCLASS_STONE_WORKS', 'YIELD_GOLD', 1),
			('POLICY_TCM_IBERIAN_BONUS_14', 'BUILDINGCLASS_STONE_WORKS', 'YIELD_FOOD', 2);

			INSERT INTO Policy_BuildingClassYieldModifiers 
			(PolicyType, 				BuildingClassType,             YieldType,		   YieldMod)
VALUES		('POLICY_TCM_IBERIAN_BONUS_4', 'BUILDINGCLASS_STONE_WORKS', 'YIELD_PRODUCTION', 5),
			('POLICY_TCM_IBERIAN_BONUS_11', 'BUILDINGCLASS_STONE_WORKS', 'YIELD_PRODUCTION', 10),
			('POLICY_TCM_IBERIAN_BONUS_15', 'BUILDINGCLASS_STONE_WORKS', 'YIELD_GOLD', 5);
			
			INSERT INTO Policy_BuildingClassYieldChanges 
			(PolicyType, 			      BuildingClassType,		    Happiness)
VALUES		('POLICY_TCM_IBERIAN_BONUS_2', 'BUILDINGCLASS_STONE_WORKS', 1),
VALUES		('POLICY_TCM_IBERIAN_BONUS_10', 'BUILDINGCLASS_STONE_WORKS', 2);