--==========================================================================================================================	
-- Diplomacy_Responses
--==========================================================================================================================			
INSERT INTO Diplomacy_Responses 
			(LeaderType, 				ResponseType, 											Response, 																	Bias)
VALUES		('LEADER_TCM_INDIBILIS', 	'RESPONSE_FIRST_GREETING', 								'TXT_KEY_LEADER_TCM_INDIBILIS_FIRSTGREETING%', 								2),	
			('LEADER_TCM_INDIBILIS', 	'RESPONSE_DEFEATED', 									'TXT_KEY_LEADER_TCM_INDIBILIS_DEFEATED%', 									2),	
			('LEADER_TCM_INDIBILIS', 	'RESPONSE_GREETING_REPEAT_TOO_MUCH', 					'TXT_KEY_LEADER_TCM_INDIBILIS_REPEAT_TOO_MUCH%', 							2),
			('LEADER_TCM_INDIBILIS', 	'RESPONSE_REPEAT_TRADE_TOO_MUCH', 						'TXT_KEY_LEADER_TCM_INDIBILIS_REPEAT_TRADE_TOO_MUCH%', 						2),
			('LEADER_TCM_INDIBILIS', 	'RESPONSE_GREETING_HOSTILE_REPEAT', 					'TXT_KEY_LEADER_TCM_INDIBILIS_REPEAT_TOO_MUCH%', 							2),
			('LEADER_TCM_INDIBILIS', 	'RESPONSE_GREETING_HOSTILE_HELLO', 						'TXT_KEY_LEADER_TCM_INDIBILIS_GREETING_HOSTILE_HELLO%', 					2),	
			('LEADER_TCM_INDIBILIS', 	'RESPONSE_GREETING_POLITE_HELLO', 						'TXT_KEY_LEADER_TCM_INDIBILIS_GREETING_POLITE_HELLO%', 						2),	
			('LEADER_TCM_INDIBILIS', 	'RESPONSE_GREETING_HOSTILE_HUMAN_AT_WAR', 				'TXT_KEY_LEADER_TCM_INDIBILIS_GREETING_HOSTILE_HUMAN_AT_WAR%', 				2),
			('LEADER_TCM_INDIBILIS', 	'RESPONSE_GREETING_HUMAN_AT_WAR', 						'TXT_KEY_LEADER_TCM_INDIBILIS_GREETING_HUMAN_AT_WAR%', 						2),
			('LEADER_TCM_INDIBILIS', 	'RESPONSE_HOSTILE_AGGRESSIVE_MILITARY_WARNING', 		'TXT_KEY_LEADER_TCM_INDIBILIS_HOSTILE_AGGRESSIVE_MILITARY_WARNING%', 		2),	
			('LEADER_TCM_INDIBILIS', 	'RESPONSE_GREETING_AGGRESSIVE_MILITARY', 				'TXT_KEY_LEADER_TCM_INDIBILIS_AGGRESSIVE_MILITARY_WARNING%', 				2),	
			('LEADER_TCM_INDIBILIS', 	'RESPONSE_GREETING_HOSTILE_AGGRESSIVE_PLOT_BUYING', 	'TXT_KEY_LEADER_TCM_INDIBILIS_GREETING_HOSTILE_AGGRESSIVE_PLOT_BUYING%', 	2),
			('LEADER_TCM_INDIBILIS', 	'RESPONSE_GREETING_AGGRESSIVE_PLOT_BUYING', 			'TXT_KEY_LEADER_TCM_INDIBILIS_GREETING_AGGRESSIVE_PLOT_BUYING%', 			2),
			('LEADER_TCM_INDIBILIS', 	'RESPONSE_GREETING_HOSTILE_AGGRESSIVE_EXPANSION', 		'TXT_KEY_LEADER_TCM_INDIBILIS_GREETING_HOSTILE_AGGRESSIVE_EXPANSION%', 		2),
			('LEADER_TCM_INDIBILIS', 	'RESPONSE_GREETING_AGGRESSIVE_EXPANSION', 				'TXT_KEY_LEADER_TCM_INDIBILIS_GREETING_AGGRESSIVE_EXPANSION%', 				2),
			('LEADER_TCM_INDIBILIS', 	'RESPONSE_GREETING_FRIENDLY_STRONG_MILITARY', 			'TXT_KEY_LEADER_TCM_INDIBILIS_GREETING_FRIENDLY_STRONG_MILITARY%', 			2),
			('LEADER_TCM_INDIBILIS', 	'RESPONSE_GREETING_FRIENDLY_STRONG_ECONOMY', 			'TXT_KEY_LEADER_TCM_INDIBILIS_GREETING_FRIENDLY_STRONG_ECONOMY%', 			2),
			('LEADER_TCM_INDIBILIS', 	'RESPONSE_GREETING_HOSTILE_HUMAN_FEW_CITIES', 			'TXT_KEY_LEADER_TCM_INDIBILIS_GREETING_HOSTILE_HUMAN_FEW_CITIES%', 			2),
			('LEADER_TCM_INDIBILIS', 	'RESPONSE_GREETING_HOSTILE_HUMAN_SMALL_ARMY', 			'TXT_KEY_LEADER_TCM_INDIBILIS_GREETING_HOSTILE_HUMAN_SMALL_ARMY%', 			2),
			('LEADER_TCM_INDIBILIS', 	'RESPONSE_GREETING_HOSTILE_HUMAN_IS_WARMONGER', 		'TXT_KEY_LEADER_TCM_INDIBILIS_GREETING_HOSTILE_HUMAN_IS_WARMONGER%', 		2),
			('LEADER_TCM_INDIBILIS', 	'RESPONSE_DONT_SETTLE_YES', 							'TXT_KEY_LEADER_TCM_INDIBILIS_DONT_SETTLE_YES%', 							2),
			('LEADER_TCM_INDIBILIS', 	'RESPONSE_DONT_SETTLE_NO', 								'TXT_KEY_LEADER_TCM_INDIBILIS_DONT_SETTLE_NO%', 							2),
			('LEADER_TCM_INDIBILIS', 	'RESPONSE_ATTACKED_HOSTILE', 							'TXT_KEY_LEADER_TCM_INDIBILIS_ATTACKED_HOSTILE%', 							2),
			('LEADER_TCM_INDIBILIS', 	'RESPONSE_ATTACKED_WEAK_HOSTILE', 						'TXT_KEY_LEADER_TCM_INDIBILIS_ATTACKED_HOSTILE%', 							2),
			('LEADER_TCM_INDIBILIS', 	'RESPONSE_ATTACKED_STRONG_HOSTILE', 					'TXT_KEY_LEADER_TCM_INDIBILIS_ATTACKED_HOSTILE%', 							2),
			('LEADER_TCM_INDIBILIS', 	'RESPONSE_ATTACKED_EXCITED', 							'TXT_KEY_LEADER_TCM_INDIBILIS_ATTACKED_EXCITED%', 							2),
			('LEADER_TCM_INDIBILIS', 	'RESPONSE_ATTACKED_WEAK_EXCITED', 						'TXT_KEY_LEADER_TCM_INDIBILIS_ATTACKED_EXCITED%', 							2),
			('LEADER_TCM_INDIBILIS', 	'RESPONSE_ATTACKED_STRONG_EXCITED', 					'TXT_KEY_LEADER_TCM_INDIBILIS_ATTACKED_EXCITED%', 							2),
			('LEADER_TCM_INDIBILIS', 	'RESPONSE_ATTACKED_SAD', 								'TXT_KEY_LEADER_TCM_INDIBILIS_ATTACKED_SAD%', 								2),
			('LEADER_TCM_INDIBILIS', 	'RESPONSE_ATTACKED_BETRAYED', 							'TXT_KEY_LEADER_TCM_INDIBILIS_ATTACKED_BETRAYED%', 							2),
			('LEADER_TCM_INDIBILIS', 	'RESPONSE_TOO_SOON_NO_PEACE', 							'TXT_KEY_LEADER_TCM_INDIBILIS_TOO_SOON_NO_PEACE%', 							2);
--==========================================================================================================================			
--==========================================================================================================================				
